In [ ]:
import pandas as pd
data = pd.read_excel("/content/Data (2).xlsx")
data

,Student_ID,Student_Name,Gender,Age,City,State,Department,Semester,Admission_Year,Study_Hours,...,Projects_Completed,Internship,Scholarship,Placement_Status,Exam_Date,Total_Marks,Percentage,Grade,Pass_Status,Remarks
0,S001,Anita_1,Male,19,Belagavi,Karnataka,MBA,1,2023,1,...,3,No,Yes,Placed,03-09-2025,70.7,70.7,B+,Pass,Needs Improvement
1,S002,Suresh_2,Male,24,Bengaluru,Karnataka,BCA,1,2023,5,...,1,Yes,No,Placed,04-10-2025,57.0,57.0,C,Pass,Good
2,S003,Suresh_3,Male,21,Hubballi,Karnataka,MBA,4,2024,8,...,3,No,No,Placed,26-03-2025,61.5,61.5,B,Pass,Good
3,S004,Asha_4,Female,25,Belagavi,Karnataka,MBA,1,2022,9,...,1,No,Yes,Not Placed,14-01-2025,77.3,77.3,B+,Pass,Excellent
4,S005,Deepa_5,Female,25,Bengaluru,Karnataka,MCA,3,2025,2,...,5,No,No,Not Placed,23-07-2025,74.7,74.7,B+,Pass,Average
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
500,S011,Rahul_11,Male,23,Mysuru,Karnataka,MBA,1,2024,2,...,2,No,Yes,Not Placed,25-04-2025,77.9,77.9,B+,Pass,Average
501,S087,Rohan_87,Female,18,Bengaluru,Karnataka,MCA,4,2025,6,...,2,Yes,Yes,Not Placed,24-07-2025,63.0,63.0,B,Pass,Good
502,S154,Vikram_154,Female,19,Mangaluru,Karnataka,BCom,4,2025,4,...,2,Yes,No,Placed,21-05-2025,60.0,60.0,B,Pass,Average
503,S259,Neha_259,Female,18,Hubballi,Karnataka,BCA,3,2025,1,...,2,Yes,Yes,Placed,05-10-2025,74.3,74.3,B+,Pass,Average
504,S332,Deepa_332,Male,19,Dharwad,Karnataka,MBA,4,2022,6,...,4,Yes,Yes,Not Placed,12-06-2025,84.0,84.0,A,Pass,Average

In [ ]:
data.head()

,Student_ID,Student_Name,Gender,Age,City,State,Department,Semester,Admission_Year,Study_Hours,...,Projects_Completed,Internship,Scholarship,Placement_Status,Exam_Date,Total_Marks,Percentage,Grade,Pass_Status,Remarks
0,S001,Anita_1,Male,19,Belagavi,Karnataka,MBA,1,2023,1,...,3,No,Yes,Placed,03-09-2025,70.7,70.7,B+,Pass,Needs Improvement
1,S002,Suresh_2,Male,24,Bengaluru,Karnataka,BCA,1,2023,5,...,1,Yes,No,Placed,04-10-2025,57.0,57.0,C,Pass,Good
2,S003,Suresh_3,Male,21,Hubballi,Karnataka,MBA,4,2024,8,...,3,No,No,Placed,26-03-2025,61.5,61.5,B,Pass,Good
3,S004,Asha_4,Female,25,Belagavi,Karnataka,MBA,1,2022,9,...,1,No,Yes,Not Placed,14-01-2025,77.3,77.3,B+,Pass,Excellent
4,S005,Deepa_5,Female,25,Bengaluru,Karnataka,MCA,3,2025,2,...,5,No,No,Not Placed,23-07-2025,74.7,74.7,B+,Pass,Average

In [ ]:
data.head(20)

,Student_ID,Student_Name,Gender,Age,City,State,Department,Semester,Admission_Year,Study_Hours,...,Projects_Completed,Internship,Scholarship,Placement_Status,Exam_Date,Total_Marks,Percentage,Grade,Pass_Status,Remarks
0,S001,Anita_1,Male,19,Belagavi,Karnataka,MBA,1,2023,1,...,3,No,Yes,Placed,03-09-2025,70.7,70.7,B+,Pass,Needs Improvement
1,S002,Suresh_2,Male,24,Bengaluru,Karnataka,BCA,1,2023,5,...,1,Yes,No,Placed,04-10-2025,57.0,57.0,C,Pass,Good
2,S003,Suresh_3,Male,21,Hubballi,Karnataka,MBA,4,2024,8,...,3,No,No,Placed,26-03-2025,61.5,61.5,B,Pass,Good
3,S004,Asha_4,Female,25,Belagavi,Karnataka,MBA,1,2022,9,...,1,No,Yes,Not Placed,14-01-2025,77.3,77.3,B+,Pass,Excellent
4,S005,Deepa_5,Female,25,Bengaluru,Karnataka,MCA,3,2025,2,...,5,No,No,Not Placed,23-07-2025,74.7,74.7,B+,Pass,Average
5,S006,Pooja_6,Male,25,Bengaluru,Karnataka,BCA,3,2023,4,...,3,No,Yes,Placed,15-07-2025,77.8,77.8,B+,Pass,Average
6,S007,Arjun_7,Female,23,Mangaluru,Karnataka,BCom,2,2023,2,...,1,Yes,Yes,Placed,16-10-2025,87.1,87.1,A,Pass,Good
7,S008,Kavya_8,Female,23,Mysuru,Karnataka,MBA,1,2025,9,...,3,No,No,Placed,16-11-2025,45.3,45.3,Fail,Fail,Needs Improvement
8,S009,Nikhil_9,Male,19,Belagavi,Karnataka,MBA,1,2022,1,...,1,Yes,No,Placed,03-04-2025,48.0,48.0,Fail,Fail,Needs Improvement
9,S010,Meena_10,Female,25,Bengaluru,Karnataka,MCA,4,2025,8,...,2,Yes,Yes,Placed,24-06-2025,67.6,67.6,B,Pass,Average
10,S011,Rahul_11,Male,23,Mysuru,Karnataka,MBA,1,2024,2,...,2,No,Yes,Not Placed,25-04-2025,77.9,77.9,B+,Pass,Average
11,S012,Rohan_12,Male,21,Dharwad,Karnataka,BCom,3,2022,1,...,3,No,Yes,Not Placed,15-12-2025,60.3,60.3,B,Pass,Average
12,S013,Neha_13,Female,21,Belagavi,Karnataka,BCA,4,2022,8,...,2,Yes,Yes,Not Placed,26-12-2025,50.8,50.8,C,Pass,Good
13,S014,Vikram_14,Male,24,Hubballi,Karnataka,BCom,1,2023,3,...,0,Yes,No,Placed,20-10-2025,74.5,74.5,B+,Pass,Needs Improvement
14,S015,Divya_15,Male,18,Bengaluru,Karnataka,MCA,2,2025,4,...,0,No,Yes,Not Placed,17-04-2025,68.9,68.9,B,Pass,Average
15,S016,Anita_16,Female,25,Mangaluru,Karnataka,MBA,4,2023,9,...,4,Yes,No,Placed,20-01-2025,62.8,62.8,B,Pass,Good
16,S017,Divya_17,Male,23,Mangaluru,Karnataka,MBA,4,2022,9,...,1,Yes,No,Placed,25-02-2025,60.0,60.0,B,Pass,Needs Improvement
17,S018,Vikram_18,Male,22,Hubballi,Karnataka,MBA,4,2023,9,...,4,Yes,No,Placed,14-02-2025,63.2,63.2,B,Pass,Needs Improvement
18,S019,Kavya_19,Male,21,Mangaluru,Karnataka,BSc,1,2023,6,...,2,Yes,No,Placed,24-02-2025,54.9,54.9,C,Pass,Needs Improvement
19,S020,Pooja_20,Female,24,Belagavi,Karnataka,BCom,2,2024,6,...,5,No,Yes,Not Placed,18-08-2025,63.2,63.2,B,Pass,Needs Improvement

In [ ]:
data.tail()

,Student_ID,Student_Name,Gender,Age,City,State,Department,Semester,Admission_Year,Study_Hours,...,Projects_Completed,Internship,Scholarship,Placement_Status,Exam_Date,Total_Marks,Percentage,Grade,Pass_Status,Remarks
500,S011,Rahul_11,Male,23,Mysuru,Karnataka,MBA,1,2024,2,...,2,No,Yes,Not Placed,25-04-2025,77.9,77.9,B+,Pass,Average
501,S087,Rohan_87,Female,18,Bengaluru,Karnataka,MCA,4,2025,6,...,2,Yes,Yes,Not Placed,24-07-2025,63.0,63.0,B,Pass,Good
502,S154,Vikram_154,Female,19,Mangaluru,Karnataka,BCom,4,2025,4,...,2,Yes,No,Placed,21-05-2025,60.0,60.0,B,Pass,Average
503,S259,Neha_259,Female,18,Hubballi,Karnataka,BCA,3,2025,1,...,2,Yes,Yes,Placed,05-10-2025,74.3,74.3,B+,Pass,Average
504,S332,Deepa_332,Male,19,Dharwad,Karnataka,MBA,4,2022,6,...,4,Yes,Yes,Not Placed,12-06-2025,84.0,84.0,A,Pass,Average

In [ ]:
data.tail(20)

,Student_ID,Student_Name,Gender,Age,City,State,Department,Semester,Admission_Year,Study_Hours,...,Projects_Completed,Internship,Scholarship,Placement_Status,Exam_Date,Total_Marks,Percentage,Grade,Pass_Status,Remarks
485,S486,Rahul_486,Male,20,Bengaluru,Karnataka,MBA,2,2024,8,...,3,Yes,Yes,Placed,12-05-2025,71.6,71.6,B+,Pass,Average
486,S487,Kavya_487,Male,25,Belagavi,Karnataka,BCA,1,2024,7,...,4,No,No,Placed,27-02-2025,65.2,65.2,B,Pass,Good
487,S488,Anita_488,Male,20,Hubballi,Karnataka,MBA,2,2025,3,...,2,Yes,Yes,Placed,07-11-2025,69.2,69.2,B,Pass,Good
488,S489,Asha_489,Female,19,Dharwad,Karnataka,BCom,3,2025,9,...,3,Yes,No,Not Placed,02-05-2025,68.7,68.7,B,Pass,Good
489,S490,Divya_490,Male,18,Mysuru,Karnataka,BCA,1,2025,1,...,1,Yes,No,Placed,01-07-2025,66.0,66.0,B,Pass,Needs Improvement
490,S491,Asha_491,Male,21,Bengaluru,Karnataka,BCom,1,2025,4,...,5,No,Yes,Not Placed,23-08-2025,61.7,61.7,B,Pass,Excellent
491,S492,Anita_492,Female,23,Dharwad,Karnataka,MBA,2,2024,8,...,0,Yes,No,Placed,22-08-2025,78.5,78.5,B+,Pass,Needs Improvement
492,S493,Divya_493,Male,18,Bengaluru,Karnataka,BCA,4,2022,9,...,0,Yes,Yes,Placed,05-06-2025,78.7,78.7,B+,Pass,Needs Improvement
493,S494,Deepa_494,Male,24,Hubballi,Karnataka,BCA,4,2023,2,...,3,Yes,No,Not Placed,12-02-2025,75.1,75.1,B+,Pass,Excellent
494,S495,Nikhil_495,Male,25,Mysuru,Karnataka,BCom,2,2023,6,...,4,Yes,No,Not Placed,10-08-2025,68.3,68.3,B,Pass,Needs Improvement
495,S496,Asha_496,Female,25,Belagavi,Karnataka,BCom,1,2023,6,...,4,No,Yes,Placed,03-02-2025,63.4,63.4,B,Pass,Good
496,S497,Amit_497,Male,22,Dharwad,Karnataka,BSc,2,2024,4,...,4,Yes,Yes,Placed,22-09-2025,67.3,67.3,B,Pass,Excellent
497,S498,Nikhil_498,Female,20,Shivamogga,Karnataka,MBA,2,2025,3,...,5,Yes,Yes,Not Placed,02-05-2025,76.2,76.2,B+,Pass,Needs Improvement
498,S499,Manoj_499,Female,19,Dharwad,Karnataka,BCom,3,2025,2,...,5,Yes,Yes,Not Placed,27-03-2025,68.8,68.8,B,Pass,Excellent
499,S500,Amit_500,Male,19,Bengaluru,Karnataka,MCA,2,2023,5,...,5,Yes,Yes,Not Placed,11-02-2025,58.3,58.3,C,Pass,Needs Improvement
500,S011,Rahul_11,Male,23,Mysuru,Karnataka,MBA,1,2024,2,...,2,No,Yes,Not Placed,25-04-2025,77.9,77.9,B+,Pass,Average
501,S087,Rohan_87,Female,18,Bengaluru,Karnataka,MCA,4,2025,6,...,2,Yes,Yes,Not Placed,24-07-2025,63.0,63.0,B,Pass,Good
502,S154,Vikram_154,Female,19,Mangaluru,Karnataka,BCom,4,2025,4,...,2,Yes,No,Placed,21-05-2025,60.0,60.0,B,Pass,Average
503,S259,Neha_259,Female,18,Hubballi,Karnataka,BCA,3,2025,1,...,2,Yes,Yes,Placed,05-10-2025,74.3,74.3,B+,Pass,Average
504,S332,Deepa_332,Male,19,Dharwad,Karnataka,MBA,4,2022,6,...,4,Yes,Yes,Not Placed,12-06-2025,84.0,84.0,A,Pass,Average

In [ ]:
data.sample()

,Student_ID,Student_Name,Gender,Age,City,State,Department,Semester,Admission_Year,Study_Hours,...,Projects_Completed,Internship,Scholarship,Placement_Status,Exam_Date,Total_Marks,Percentage,Grade,Pass_Status,Remarks
283,S284,Amit_284,Female,19,Mysuru,Karnataka,MBA,3,2024,2,...,5,Yes,Yes,Not Placed,24-07-2025,60.6,60.6,B,Pass,Good

In [ ]:
data.sample(5)

,Student_ID,Student_Name,Gender,Age,City,State,Department,Semester,Admission_Year,Study_Hours,...,Projects_Completed,Internship,Scholarship,Placement_Status,Exam_Date,Total_Marks,Percentage,Grade,Pass_Status,Remarks
474,S475,Arjun_475,Male,23,Mysuru,Karnataka,BCom,2,2024,8,...,5,Yes,No,Not Placed,27-09-2025,59.1,59.1,C,Pass,Good
264,S265,Rohan_265,Female,19,Hubballi,Karnataka,MBA,4,2024,10,...,2,No,No,Not Placed,06-08-2025,60.7,60.7,B,Pass,Excellent
405,S406,Pooja_406,Female,19,Belagavi,Karnataka,MBA,4,2023,1,...,5,Yes,Yes,Not Placed,22-10-2025,56.6,56.6,C,Pass,Needs Improvement
91,S092,Divya_92,Male,22,Hubballi,Karnataka,BCA,2,2025,8,...,0,No,No,Placed,23-08-2025,61.1,61.1,B,Pass,Good
58,S059,Suresh_59,Female,20,Mysuru,Karnataka,BSc,3,2023,9,...,0,Yes,No,Not Placed,25-04-2025,66.2,66.2,B,Pass,Average

In [ ]:
type(data)

pandas.core.frame.DataFrame

In [ ]:
data["Gender"]

0        Male
1        Male
2        Male
3      Female
4      Female
        ...
500      Male
501    Female
502    Female
503    Female
504      Male
Name: Gender, Length: 505, dtype: object

In [ ]:
data["Admission_Year"]

0      2023
1      2023
2      2024
3      2022
4      2025
       ...
500    2024
501    2025
502    2025
503    2025
504    2022
Name: Admission_Year, Length: 505, dtype: int64

In [ ]:
df = pd.DataFrame(data)
type(df)

pandas.core.frame.DataFrame

In [ ]:
df.shape

(505, 25)

In [ ]:
len(data)

505

In [ ]:
len(data.columns)

25

In [ ]:
data.columns

Index(['Student_ID', 'Student_Name', 'Gender', 'Age', 'City', 'State',
       'Department', 'Semester', 'Admission_Year', 'Study_Hours', 'Attendance',
       'Assignment_Score', 'Quiz_Score', 'Internal_Marks', 'Final_Exam_Marks',
       'Projects_Completed', 'Internship', 'Scholarship', 'Placement_Status',
       'Exam_Date', 'Total_Marks', 'Percentage', 'Grade', 'Pass_Status',
       'Remarks'],
      dtype='object')

In [ ]:
data.info

<bound method DataFrame.info of     Student_ID Student_Name  Gender  Age       City      State Department  \
0         S001      Anita_1    Male   19   Belagavi  Karnataka        MBA
1         S002     Suresh_2    Male   24  Bengaluru  Karnataka        BCA
2         S003     Suresh_3    Male   21   Hubballi  Karnataka        MBA
3         S004       Asha_4  Female   25   Belagavi  Karnataka        MBA
4         S005      Deepa_5  Female   25  Bengaluru  Karnataka        MCA
..         ...          ...     ...  ...        ...        ...        ...
500       S011     Rahul_11    Male   23     Mysuru  Karnataka        MBA
501       S087     Rohan_87  Female   18  Bengaluru  Karnataka        MCA
502       S154   Vikram_154  Female   19  Mangaluru  Karnataka       BCom
503       S259     Neha_259  Female   18   Hubballi  Karnataka        BCA
504       S332    Deepa_332    Male   19    Dharwad  Karnataka        MBA

     Semester  Admission_Year  Study_Hours  ...  Projects_Completed  \
0           1            2023            1  ...                   3
1           1            2023            5  ...                   1
2           4            2024            8  ...                   3
3           1            2022            9  ...                   1
4           3            2025            2  ...                   5
..        ...             ...          ...  ...                 ...
500         1            2024            2  ...                   2
501         4            2025            6  ...                   2
502         4            2025            4  ...                   2
503         3            2025            1  ...                   2
504         4            2022            6  ...                   4

     Internship  Scholarship  Placement_Status   Exam_Date  Total_Marks  \
0            No          Yes            Placed  03-09-2025         70.7
1           Yes           No            Placed  04-10-2025         57.0
2            No           No            Placed  26-03-2025         61.5
3            No          Yes        Not Placed  14-01-2025         77.3
4            No           No        Not Placed  23-07-2025         74.7
..          ...          ...               ...         ...          ...
500          No          Yes        Not Placed  25-04-2025         77.9
501         Yes          Yes        Not Placed  24-07-2025         63.0
502         Yes           No            Placed  21-05-2025         60.0
503         Yes          Yes            Placed  05-10-2025         74.3
504         Yes          Yes        Not Placed  12-06-2025         84.0

    Percentage Grade Pass_Status            Remarks
0         70.7    B+        Pass  Needs Improvement
1         57.0     C        Pass               Good
2         61.5     B        Pass               Good
3         77.3    B+        Pass          Excellent
4         74.7    B+        Pass            Average
..         ...   ...         ...                ...
500       77.9    B+        Pass            Average
501       63.0     B        Pass               Good
502       60.0     B        Pass            Average
503       74.3    B+        Pass            Average
504       84.0     A        Pass            Average

[505 rows x 25 columns]>

In [ ]:
data.dtypes

Student_ID             object
Student_Name           object
Gender                 object
Age                     int64
City                   object
State                  object
Department             object
Semester                int64
Admission_Year          int64
Study_Hours             int64
Attendance            float64
Assignment_Score        int64
Quiz_Score              int64
Internal_Marks          int64
Final_Exam_Marks      float64
Projects_Completed      int64
Internship             object
Scholarship            object
Placement_Status       object
Exam_Date              object
Total_Marks           float64
Percentage            float64
Grade                  object
Pass_Status            object
Remarks                object
dtype: object

In [ ]:
data.describe()

,Age,Semester,Admission_Year,Study_Hours,Attendance,Assignment_Score,Quiz_Score,Internal_Marks,Final_Exam_Marks,Projects_Completed,Total_Marks,Percentage
count,505.000000,505.000000,505.000000,505.000000,504.000000,505.000000,505.000000,505.000000,504.000000,505.000000,505.000000,505.000000
mean,21.396040,2.508911,2023.534653,5.461386,76.650794,69.322772,69.639604,66.063366,65.289683,2.502970,66.794257,66.794257
std,2.277736,1.160024,1.081632,2.924139,13.268488,17.954881,17.412731,20.680582,19.723219,1.723004,10.407003,10.407003
min,18.000000,1.000000,2022.000000,1.000000,55.000000,40.000000,40.000000,30.000000,30.000000,0.000000,39.200000,39.200000
25%,19.000000,1.000000,2023.000000,3.000000,65.000000,54.000000,55.000000,48.000000,48.000000,1.000000,59.500000,59.500000
50%,21.000000,3.000000,2024.000000,6.000000,77.000000,69.000000,69.000000,66.000000,65.000000,2.000000,66.600000,66.600000
75%,23.000000,4.000000,2024.000000,8.000000,88.000000,85.000000,85.000000,84.000000,82.000000,4.000000,74.300000,74.300000
max,25.000000,4.000000,2025.000000,10.000000,100.000000,100.000000,100.000000,100.000000,100.000000,5.000000,93.800000,93.800000

In [ ]:
data.describe(include="all")

,Student_ID,Student_Name,Gender,Age,City,State,Department,Semester,Admission_Year,Study_Hours,...,Projects_Completed,Internship,Scholarship,Placement_Status,Exam_Date,Total_Marks,Percentage,Grade,Pass_Status,Remarks
count,505,504,505,505.000000,505,505,504,505.000000,505.000000,505.000000,...,505.000000,505,505,505,504,505.000000,505.000000,505,505,505
unique,500,499,2,NaN,7,1,5,NaN,NaN,NaN,...,NaN,2,2,2,265,NaN,NaN,6,2,4
top,S332,Deepa_332,Male,NaN,Bengaluru,Karnataka,BCom,NaN,NaN,NaN,...,NaN,Yes,Yes,Placed,17-01-2025,NaN,NaN,B,Pass,Good
freq,2,2,260,NaN,81,505,114,NaN,NaN,NaN,...,NaN,280,255,283,7,NaN,NaN,172,479,135
mean,NaN,NaN,NaN,21.396040,NaN,NaN,NaN,2.508911,2023.534653,5.461386,...,2.502970,NaN,NaN,NaN,NaN,66.794257,66.794257,NaN,NaN,NaN
std,NaN,NaN,NaN,2.277736,NaN,NaN,NaN,1.160024,1.081632,2.924139,...,1.723004,NaN,NaN,NaN,NaN,10.407003,10.407003,NaN,NaN,NaN
min,NaN,NaN,NaN,18.000000,NaN,NaN,NaN,1.000000,2022.000000,1.000000,...,0.000000,NaN,NaN,NaN,NaN,39.200000,39.200000,NaN,NaN,NaN
25%,NaN,NaN,NaN,19.000000,NaN,NaN,NaN,1.000000,2023.000000,3.000000,...,1.000000,NaN,NaN,NaN,NaN,59.500000,59.500000,NaN,NaN,NaN
50%,NaN,NaN,NaN,21.000000,NaN,NaN,NaN,3.000000,2024.000000,6.000000,...,2.000000,NaN,NaN,NaN,NaN,66.600000,66.600000,NaN,NaN,NaN
75%,NaN,NaN,NaN,23.000000,NaN,NaN,NaN,4.000000,2024.000000,8.000000,...,4.000000,NaN,NaN,NaN,NaN,74.300000,74.300000,NaN,NaN,NaN
max,NaN,NaN,NaN,25.000000,NaN,NaN,NaN,4.000000,2025.000000,10.000000,...,5.000000,NaN,NaN,NaN,NaN,93.800000,93.800000,NaN,NaN,NaN

In [ ]:
data.index

RangeIndex(start=0, stop=505, step=1)

In [ ]:
data.count()

Student_ID            505
Student_Name          504
Gender                505
Age                   505
City                  505
State                 505
Department            504
Semester              505
Admission_Year        505
Study_Hours           505
Attendance            504
Assignment_Score      505
Quiz_Score            505
Internal_Marks        505
Final_Exam_Marks      504
Projects_Completed    505
Internship            505
Scholarship           505
Placement_Status      505
Exam_Date             504
Total_Marks           505
Percentage            505
Grade                 505
Pass_Status           505
Remarks               505
dtype: int64

In [ ]:
data.isnull()

,Student_ID,Student_Name,Gender,Age,City,State,Department,Semester,Admission_Year,Study_Hours,...,Projects_Completed,Internship,Scholarship,Placement_Status,Exam_Date,Total_Marks,Percentage,Grade,Pass_Status,Remarks
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
500,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
501,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
502,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
503,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
504,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [ ]:
data.isnull().sum()

Student_ID            0
Student_Name          1
Gender                0
Age                   0
City                  0
State                 0
Department            1
Semester              0
Admission_Year        0
Study_Hours           0
Attendance            1
Assignment_Score      0
Quiz_Score            0
Internal_Marks        0
Final_Exam_Marks      1
Projects_Completed    0
Internship            0
Scholarship           0
Placement_Status      0
Exam_Date             1
Total_Marks           0
Percentage            0
Grade                 0
Pass_Status           0
Remarks               0
dtype: int64

In [ ]:
data.duplicated()

0      False
1      False
2      False
3      False
4      False
       ...
500     True
501     True
502     True
503     True
504     True
Length: 505, dtype: bool

In [ ]:
data.duplicated().sum()

np.int64(5)

In [ ]:
data.nunique()

Student_ID            500
Student_Name          499
Gender                  2
Age                     8
City                    7
State                   1
Department              5
Semester                4
Admission_Year          4
Study_Hours            10
Attendance             46
Assignment_Score       61
Quiz_Score             61
Internal_Marks         71
Final_Exam_Marks       71
Projects_Completed      6
Internship              2
Scholarship             2
Placement_Status        2
Exam_Date             265
Total_Marks           288
Percentage            288
Grade                   6
Pass_Status             2
Remarks                 4
dtype: int64

In [ ]:
data["Gender"].unique()

array(['Male', 'Female'], dtype=object)

In [ ]:
data["Department"].unique()

array(['MBA', 'BCA', 'MCA', 'BCom', 'BSc', nan], dtype=object)

In [ ]:
data["Admission_Year"].unique()

array([2023, 2024, 2022, 2025])

In [ ]:
data["Gender"].value_counts()

Gender
Male      260
Female    245
Name: count, dtype: int64

In [ ]:
data["Department"].value_counts()

Department
BCom    114
MBA     103
BSc      98
BCA      96
MCA      93
Name: count, dtype: int64

In [ ]:
data.memory_usage()

Index                  132
Student_ID            4040
Student_Name          4040
Gender                4040
Age                   4040
City                  4040
State                 4040
Department            4040
Semester              4040
Admission_Year        4040
Study_Hours           4040
Attendance            4040
Assignment_Score      4040
Quiz_Score            4040
Internal_Marks        4040
Final_Exam_Marks      4040
Projects_Completed    4040
Internship            4040
Scholarship           4040
Placement_Status      4040
Exam_Date             4040
Total_Marks           4040
Percentage            4040
Grade                 4040
Pass_Status           4040
Remarks               4040
dtype: int64

In [ ]:
# data cleaning
data.copy()

,Student_ID,Student_Name,Gender,Age,City,State,Department,Semester,Admission_Year,Study_Hours,...,Projects_Completed,Internship,Scholarship,Placement_Status,Exam_Date,Total_Marks,Percentage,Grade,Pass_Status,Remarks
0,S001,Anita_1,Male,19,Belagavi,Karnataka,MBA,1,2023,1,...,3,No,Yes,Placed,03-09-2025,70.7,70.7,B+,Pass,Needs Improvement
1,S002,Suresh_2,Male,24,Bengaluru,Karnataka,BCA,1,2023,5,...,1,Yes,No,Placed,04-10-2025,57.0,57.0,C,Pass,Good
2,S003,Suresh_3,Male,21,Hubballi,Karnataka,MBA,4,2024,8,...,3,No,No,Placed,26-03-2025,61.5,61.5,B,Pass,Good
3,S004,Asha_4,Female,25,Belagavi,Karnataka,MBA,1,2022,9,...,1,No,Yes,Not Placed,14-01-2025,77.3,77.3,B+,Pass,Excellent
4,S005,Deepa_5,Female,25,Bengaluru,Karnataka,MCA,3,2025,2,...,5,No,No,Not Placed,23-07-2025,74.7,74.7,B+,Pass,Average
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
500,S011,Rahul_11,Male,23,Mysuru,Karnataka,MBA,1,2024,2,...,2,No,Yes,Not Placed,25-04-2025,77.9,77.9,B+,Pass,Average
501,S087,Rohan_87,Female,18,Bengaluru,Karnataka,MCA,4,2025,6,...,2,Yes,Yes,Not Placed,24-07-2025,63.0,63.0,B,Pass,Good
502,S154,Vikram_154,Female,19,Mangaluru,Karnataka,BCom,4,2025,4,...,2,Yes,No,Placed,21-05-2025,60.0,60.0,B,Pass,Average
503,S259,Neha_259,Female,18,Hubballi,Karnataka,BCA,3,2025,1,...,2,Yes,Yes,Placed,05-10-2025,74.3,74.3,B+,Pass,Average
504,S332,Deepa_332,Male,19,Dharwad,Karnataka,MBA,4,2022,6,...,4,Yes,Yes,Not Placed,12-06-2025,84.0,84.0,A,Pass,Average

In [ ]:
clean_data = data.copy()
clean_data

,Student_ID,Student_Name,Gender,Age,City,State,Department,Semester,Admission_Year,Study_Hours,...,Projects_Completed,Internship,Scholarship,Placement_Status,Exam_Date,Total_Marks,Percentage,Grade,Pass_Status,Remarks
0,S001,Anita_1,Male,19,Belagavi,Karnataka,MBA,1,2023,1,...,3,No,Yes,Placed,03-09-2025,70.7,70.7,B+,Pass,Needs Improvement
1,S002,Suresh_2,Male,24,Bengaluru,Karnataka,BCA,1,2023,5,...,1,Yes,No,Placed,04-10-2025,57.0,57.0,C,Pass,Good
2,S003,Suresh_3,Male,21,Hubballi,Karnataka,MBA,4,2024,8,...,3,No,No,Placed,26-03-2025,61.5,61.5,B,Pass,Good
3,S004,Asha_4,Female,25,Belagavi,Karnataka,MBA,1,2022,9,...,1,No,Yes,Not Placed,14-01-2025,77.3,77.3,B+,Pass,Excellent
4,S005,Deepa_5,Female,25,Bengaluru,Karnataka,MCA,3,2025,2,...,5,No,No,Not Placed,23-07-2025,74.7,74.7,B+,Pass,Average
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
500,S011,Rahul_11,Male,23,Mysuru,Karnataka,MBA,1,2024,2,...,2,No,Yes,Not Placed,25-04-2025,77.9,77.9,B+,Pass,Average
501,S087,Rohan_87,Female,18,Bengaluru,Karnataka,MCA,4,2025,6,...,2,Yes,Yes,Not Placed,24-07-2025,63.0,63.0,B,Pass,Good
502,S154,Vikram_154,Female,19,Mangaluru,Karnataka,BCom,4,2025,4,...,2,Yes,No,Placed,21-05-2025,60.0,60.0,B,Pass,Average
503,S259,Neha_259,Female,18,Hubballi,Karnataka,BCA,3,2025,1,...,2,Yes,Yes,Placed,05-10-2025,74.3,74.3,B+,Pass,Average
504,S332,Deepa_332,Male,19,Dharwad,Karnataka,MBA,4,2022,6,...,4,Yes,Yes,Not Placed,12-06-2025,84.0,84.0,A,Pass,Average

In [ ]:
clean_data.isnull()

,Student_ID,Student_Name,Gender,Age,City,State,Department,Semester,Admission_Year,Study_Hours,...,Projects_Completed,Internship,Scholarship,Placement_Status,Exam_Date,Total_Marks,Percentage,Grade,Pass_Status,Remarks
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
500,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
501,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
502,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
503,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
504,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [ ]:
clean_data.isnull().sum()

Student_ID            0
Student_Name          1
Gender                0
Age                   0
City                  0
State                 0
Department            1
Semester              0
Admission_Year        0
Study_Hours           0
Attendance            1
Assignment_Score      0
Quiz_Score            0
Internal_Marks        0
Final_Exam_Marks      1
Projects_Completed    0
Internship            0
Scholarship           0
Placement_Status      0
Exam_Date             1
Total_Marks           0
Percentage            0
Grade                 0
Pass_Status           0
Remarks               0
dtype: int64

In [ ]:
clean_data[clean_data.isnull().any(axis=1)]

,Student_ID,Student_Name,Gender,Age,City,State,Department,Semester,Admission_Year,Study_Hours,...,Projects_Completed,Internship,Scholarship,Placement_Status,Exam_Date,Total_Marks,Percentage,Grade,Pass_Status,Remarks
23,S024,Ravi_24,Female,25,Dharwad,Karnataka,BCA,3,2024,1,...,0,Yes,Yes,Placed,17-08-2025,83.2,83.2,A,Pass,Good
75,S076,NaN,Male,20,Bengaluru,Karnataka,BCA,3,2024,6,...,2,Yes,No,Not Placed,10-01-2025,51.3,51.3,C,Pass,Average
121,S122,Neha_122,Male,25,Mangaluru,Karnataka,NaN,2,2022,7,...,3,Yes,No,Placed,25-06-2025,74.9,74.9,B+,Pass,Average
248,S249,Vikram_249,Female,21,Bengaluru,Karnataka,BCom,2,2022,4,...,5,No,No,Placed,28-04-2025,70.9,70.9,B+,Pass,Excellent
399,S400,Asha_400,Male,20,Shivamogga,Karnataka,MBA,4,2023,9,...,2,No,Yes,Placed,NaN,73.7,73.7,B+,Pass,Average

In [ ]:
clean_data.isnull().sum().sum()

np.int64(5)

In [ ]:
data = clean_data.dropna()
data

,Student_ID,Student_Name,Gender,Age,City,State,Department,Semester,Admission_Year,Study_Hours,...,Projects_Completed,Internship,Scholarship,Placement_Status,Exam_Date,Total_Marks,Percentage,Grade,Pass_Status,Remarks
0,S001,Anita_1,Male,19,Belagavi,Karnataka,MBA,1,2023,1,...,3,No,Yes,Placed,03-09-2025,70.7,70.7,B+,Pass,Needs Improvement
1,S002,Suresh_2,Male,24,Bengaluru,Karnataka,BCA,1,2023,5,...,1,Yes,No,Placed,04-10-2025,57.0,57.0,C,Pass,Good
2,S003,Suresh_3,Male,21,Hubballi,Karnataka,MBA,4,2024,8,...,3,No,No,Placed,26-03-2025,61.5,61.5,B,Pass,Good
3,S004,Asha_4,Female,25,Belagavi,Karnataka,MBA,1,2022,9,...,1,No,Yes,Not Placed,14-01-2025,77.3,77.3,B+,Pass,Excellent
4,S005,Deepa_5,Female,25,Bengaluru,Karnataka,MCA,3,2025,2,...,5,No,No,Not Placed,23-07-2025,74.7,74.7,B+,Pass,Average
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
500,S011,Rahul_11,Male,23,Mysuru,Karnataka,MBA,1,2024,2,...,2,No,Yes,Not Placed,25-04-2025,77.9,77.9,B+,Pass,Average
501,S087,Rohan_87,Female,18,Bengaluru,Karnataka,MCA,4,2025,6,...,2,Yes,Yes,Not Placed,24-07-2025,63.0,63.0,B,Pass,Good
502,S154,Vikram_154,Female,19,Mangaluru,Karnataka,BCom,4,2025,4,...,2,Yes,No,Placed,21-05-2025,60.0,60.0,B,Pass,Average
503,S259,Neha_259,Female,18,Hubballi,Karnataka,BCA,3,2025,1,...,2,Yes,Yes,Placed,05-10-2025,74.3,74.3,B+,Pass,Average
504,S332,Deepa_332,Male,19,Dharwad,Karnataka,MBA,4,2022,6,...,4,Yes,Yes,Not Placed,12-06-2025,84.0,84.0,A,Pass,Average

In [ ]:
clean_data["Attendance"] = clean_data["Attendance"].fillna(clean_data["Attendance"].median())

In [ ]:
clean_data["Gender"] = clean_data["Gender"].fillna(clean_data["Gender"].mode(0))
clean_data

,Student_ID,Student_Name,Gender,Age,City,State,Department,Semester,Admission_Year,Study_Hours,...,Projects_Completed,Internship,Scholarship,Placement_Status,Exam_Date,Total_Marks,Percentage,Grade,Pass_Status,Remarks
0,S001,Anita_1,Male,19,Belagavi,Karnataka,MBA,1,2023,1,...,3,No,Yes,Placed,03-09-2025,70.7,70.7,B+,Pass,Needs Improvement
1,S002,Suresh_2,Male,24,Bengaluru,Karnataka,BCA,1,2023,5,...,1,Yes,No,Placed,04-10-2025,57.0,57.0,C,Pass,Good
2,S003,Suresh_3,Male,21,Hubballi,Karnataka,MBA,4,2024,8,...,3,No,No,Placed,26-03-2025,61.5,61.5,B,Pass,Good
3,S004,Asha_4,Female,25,Belagavi,Karnataka,MBA,1,2022,9,...,1,No,Yes,Not Placed,14-01-2025,77.3,77.3,B+,Pass,Excellent
4,S005,Deepa_5,Female,25,Bengaluru,Karnataka,MCA,3,2025,2,...,5,No,No,Not Placed,23-07-2025,74.7,74.7,B+,Pass,Average
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
500,S011,Rahul_11,Male,23,Mysuru,Karnataka,MBA,1,2024,2,...,2,No,Yes,Not Placed,25-04-2025,77.9,77.9,B+,Pass,Average
501,S087,Rohan_87,Female,18,Bengaluru,Karnataka,MCA,4,2025,6,...,2,Yes,Yes,Not Placed,24-07-2025,63.0,63.0,B,Pass,Good
502,S154,Vikram_154,Female,19,Mangaluru,Karnataka,BCom,4,2025,4,...,2,Yes,No,Placed,21-05-2025,60.0,60.0,B,Pass,Average
503,S259,Neha_259,Female,18,Hubballi,Karnataka,BCA,3,2025,1,...,2,Yes,Yes,Placed,05-10-2025,74.3,74.3,B+,Pass,Average
504,S332,Deepa_332,Male,19,Dharwad,Karnataka,MBA,4,2022,6,...,4,Yes,Yes,Not Placed,12-06-2025,84.0,84.0,A,Pass,Average

In [ ]:
clean_data["Study_Hours"] = clean_data["Study_Hours"].fillna(clean_data["Study_Hours"].mean())
clean_data

,Student_ID,Student_Name,Gender,Age,City,State,Department,Semester,Admission_Year,Study_Hours,...,Projects_Completed,Internship,Scholarship,Placement_Status,Exam_Date,Total_Marks,Percentage,Grade,Pass_Status,Remarks
0,S001,Anita_1,Male,19,Belagavi,Karnataka,MBA,1,2023,1,...,3,No,Yes,Placed,03-09-2025,70.7,70.7,B+,Pass,Needs Improvement
1,S002,Suresh_2,Male,24,Bengaluru,Karnataka,BCA,1,2023,5,...,1,Yes,No,Placed,04-10-2025,57.0,57.0,C,Pass,Good
2,S003,Suresh_3,Male,21,Hubballi,Karnataka,MBA,4,2024,8,...,3,No,No,Placed,26-03-2025,61.5,61.5,B,Pass,Good
3,S004,Asha_4,Female,25,Belagavi,Karnataka,MBA,1,2022,9,...,1,No,Yes,Not Placed,14-01-2025,77.3,77.3,B+,Pass,Excellent
4,S005,Deepa_5,Female,25,Bengaluru,Karnataka,MCA,3,2025,2,...,5,No,No,Not Placed,23-07-2025,74.7,74.7,B+,Pass,Average
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
500,S011,Rahul_11,Male,23,Mysuru,Karnataka,MBA,1,2024,2,...,2,No,Yes,Not Placed,25-04-2025,77.9,77.9,B+,Pass,Average
501,S087,Rohan_87,Female,18,Bengaluru,Karnataka,MCA,4,2025,6,...,2,Yes,Yes,Not Placed,24-07-2025,63.0,63.0,B,Pass,Good
502,S154,Vikram_154,Female,19,Mangaluru,Karnataka,BCom,4,2025,4,...,2,Yes,No,Placed,21-05-2025,60.0,60.0,B,Pass,Average
503,S259,Neha_259,Female,18,Hubballi,Karnataka,BCA,3,2025,1,...,2,Yes,Yes,Placed,05-10-2025,74.3,74.3,B+,Pass,Average
504,S332,Deepa_332,Male,19,Dharwad,Karnataka,MBA,4,2022,6,...,4,Yes,Yes,Not Placed,12-06-2025,84.0,84.0,A,Pass,Average

In [ ]:
clean_data.duplicated().sum()

np.int64(5)

In [ ]:
clean_data[clean_data.duplicated()]

,Student_ID,Student_Name,Gender,Age,City,State,Department,Semester,Admission_Year,Study_Hours,...,Projects_Completed,Internship,Scholarship,Placement_Status,Exam_Date,Total_Marks,Percentage,Grade,Pass_Status,Remarks
500,S011,Rahul_11,Male,23,Mysuru,Karnataka,MBA,1,2024,2,...,2,No,Yes,Not Placed,25-04-2025,77.9,77.9,B+,Pass,Average
501,S087,Rohan_87,Female,18,Bengaluru,Karnataka,MCA,4,2025,6,...,2,Yes,Yes,Not Placed,24-07-2025,63.0,63.0,B,Pass,Good
502,S154,Vikram_154,Female,19,Mangaluru,Karnataka,BCom,4,2025,4,...,2,Yes,No,Placed,21-05-2025,60.0,60.0,B,Pass,Average
503,S259,Neha_259,Female,18,Hubballi,Karnataka,BCA,3,2025,1,...,2,Yes,Yes,Placed,05-10-2025,74.3,74.3,B+,Pass,Average
504,S332,Deepa_332,Male,19,Dharwad,Karnataka,MBA,4,2022,6,...,4,Yes,Yes,Not Placed,12-06-2025,84.0,84.0,A,Pass,Average

In [ ]:
clean_data = clean_data.drop_duplicates()
clean_data

,Student_ID,Student_Name,Gender,Age,City,State,Department,Semester,Admission_Year,Study_Hours,...,Projects_Completed,Internship,Scholarship,Placement_Status,Exam_Date,Total_Marks,Percentage,Grade,Pass_Status,Remarks
0,S001,Anita_1,Male,19,Belagavi,Karnataka,MBA,1,2023,1,...,3,No,Yes,Placed,03-09-2025,70.7,70.7,B+,Pass,Needs Improvement
1,S002,Suresh_2,Male,24,Bengaluru,Karnataka,BCA,1,2023,5,...,1,Yes,No,Placed,04-10-2025,57.0,57.0,C,Pass,Good
2,S003,Suresh_3,Male,21,Hubballi,Karnataka,MBA,4,2024,8,...,3,No,No,Placed,26-03-2025,61.5,61.5,B,Pass,Good
3,S004,Asha_4,Female,25,Belagavi,Karnataka,MBA,1,2022,9,...,1,No,Yes,Not Placed,14-01-2025,77.3,77.3,B+,Pass,Excellent
4,S005,Deepa_5,Female,25,Bengaluru,Karnataka,MCA,3,2025,2,...,5,No,No,Not Placed,23-07-2025,74.7,74.7,B+,Pass,Average
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,S496,Asha_496,Female,25,Belagavi,Karnataka,BCom,1,2023,6,...,4,No,Yes,Placed,03-02-2025,63.4,63.4,B,Pass,Good
496,S497,Amit_497,Male,22,Dharwad,Karnataka,BSc,2,2024,4,...,4,Yes,Yes,Placed,22-09-2025,67.3,67.3,B,Pass,Excellent
497,S498,Nikhil_498,Female,20,Shivamogga,Karnataka,MBA,2,2025,3,...,5,Yes,Yes,Not Placed,02-05-2025,76.2,76.2,B+,Pass,Needs Improvement
498,S499,Manoj_499,Female,19,Dharwad,Karnataka,BCom,3,2025,2,...,5,Yes,Yes,Not Placed,27-03-2025,68.8,68.8,B,Pass,Excellent
499,S500,Amit_500,Male,19,Bengaluru,Karnataka,MCA,2,2023,5,...,5,Yes,Yes,Not Placed,11-02-2025,58.3,58.3,C,Pass,Needs Improvement

In [ ]:
clean_data["Age"] = clean_data["Age"].astype(int)
clean_data

,Student_ID,Student_Name,Gender,Age,City,State,Department,Semester,Admission_Year,Study_Hours,...,Projects_Completed,Internship,Scholarship,Placement_Status,Exam_Date,Total_Marks,Percentage,Grade,Pass_Status,Remarks
0,S001,Anita_1,Male,19,Belagavi,Karnataka,MBA,1,2023,1,...,3,No,Yes,Placed,03-09-2025,70.7,70,B+,Pass,Needs Improvement
1,S002,Suresh_2,Male,24,Bengaluru,Karnataka,BCA,1,2023,5,...,1,Yes,No,Placed,04-10-2025,57.0,57,C,Pass,Good
2,S003,Suresh_3,Male,21,Hubballi,Karnataka,MBA,4,2024,8,...,3,No,No,Placed,26-03-2025,61.5,61,B,Pass,Good
3,S004,Asha_4,Female,25,Belagavi,Karnataka,MBA,1,2022,9,...,1,No,Yes,Not Placed,14-01-2025,77.3,77,B+,Pass,Excellent
4,S005,Deepa_5,Female,25,Bengaluru,Karnataka,MCA,3,2025,2,...,5,No,No,Not Placed,23-07-2025,74.7,74,B+,Pass,Average
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,S496,Asha_496,Female,25,Belagavi,Karnataka,BCom,1,2023,6,...,4,No,Yes,Placed,03-02-2025,63.4,63,B,Pass,Good
496,S497,Amit_497,Male,22,Dharwad,Karnataka,BSc,2,2024,4,...,4,Yes,Yes,Placed,22-09-2025,67.3,67,B,Pass,Excellent
497,S498,Nikhil_498,Female,20,Shivamogga,Karnataka,MBA,2,2025,3,...,5,Yes,Yes,Not Placed,02-05-2025,76.2,76,B+,Pass,Needs Improvement
498,S499,Manoj_499,Female,19,Dharwad,Karnataka,BCom,3,2025,2,...,5,Yes,Yes,Not Placed,27-03-2025,68.8,68,B,Pass,Excellent
499,S500,Amit_500,Male,19,Bengaluru,Karnataka,MCA,2,2023,5,...,5,Yes,Yes,Not Placed,11-02-2025,58.3,58,C,Pass,Needs Improvement

In [ ]:
clean_data["Percentage"] = clean_data["Percentage"].astype(int)
clean_data

,Student_ID,Student_Name,Gender,Age,City,State,Department,Semester,Admission_Year,Study_Hours,...,Projects_Completed,Internship,Scholarship,Placement_Status,Exam_Date,Total_Marks,Percentage,Grade,Pass_Status,Remarks
0,S001,Anita_1,Male,19,Belagavi,Karnataka,MBA,1,2023,1,...,3,No,Yes,Placed,03-09-2025,70.7,70,B+,Pass,Needs Improvement
1,S002,Suresh_2,Male,24,Bengaluru,Karnataka,BCA,1,2023,5,...,1,Yes,No,Placed,04-10-2025,57.0,57,C,Pass,Good
2,S003,Suresh_3,Male,21,Hubballi,Karnataka,MBA,4,2024,8,...,3,No,No,Placed,26-03-2025,61.5,61,B,Pass,Good
3,S004,Asha_4,Female,25,Belagavi,Karnataka,MBA,1,2022,9,...,1,No,Yes,Not Placed,14-01-2025,77.3,77,B+,Pass,Excellent
4,S005,Deepa_5,Female,25,Bengaluru,Karnataka,MCA,3,2025,2,...,5,No,No,Not Placed,23-07-2025,74.7,74,B+,Pass,Average
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,S496,Asha_496,Female,25,Belagavi,Karnataka,BCom,1,2023,6,...,4,No,Yes,Placed,03-02-2025,63.4,63,B,Pass,Good
496,S497,Amit_497,Male,22,Dharwad,Karnataka,BSc,2,2024,4,...,4,Yes,Yes,Placed,22-09-2025,67.3,67,B,Pass,Excellent
497,S498,Nikhil_498,Female,20,Shivamogga,Karnataka,MBA,2,2025,3,...,5,Yes,Yes,Not Placed,02-05-2025,76.2,76,B+,Pass,Needs Improvement
498,S499,Manoj_499,Female,19,Dharwad,Karnataka,BCom,3,2025,2,...,5,Yes,Yes,Not Placed,27-03-2025,68.8,68,B,Pass,Excellent
499,S500,Amit_500,Male,19,Bengaluru,Karnataka,MCA,2,2023,5,...,5,Yes,Yes,Not Placed,11-02-2025,58.3,58,C,Pass,Needs Improvement

In [ ]:
clean_data["Gender"] = clean_data["Gender"].str.strip()
clean_data

,Student_ID,Student_Name,Gender,Age,City,State,Department,Semester,Admission_Year,Study_Hours,...,Projects_Completed,Internship,Scholarship,Placement_Status,Exam_Date,Total_Marks,Percentage,Grade,Pass_Status,Remarks
0,S001,Anita_1,Male,19,Belagavi,Karnataka,MBA,1,2023,1,...,3,No,Yes,Placed,03-09-2025,70.7,70,B+,Pass,Needs Improvement
1,S002,Suresh_2,Male,24,Bengaluru,Karnataka,BCA,1,2023,5,...,1,Yes,No,Placed,04-10-2025,57.0,57,C,Pass,Good
2,S003,Suresh_3,Male,21,Hubballi,Karnataka,MBA,4,2024,8,...,3,No,No,Placed,26-03-2025,61.5,61,B,Pass,Good
3,S004,Asha_4,Female,25,Belagavi,Karnataka,MBA,1,2022,9,...,1,No,Yes,Not Placed,14-01-2025,77.3,77,B+,Pass,Excellent
4,S005,Deepa_5,Female,25,Bengaluru,Karnataka,MCA,3,2025,2,...,5,No,No,Not Placed,23-07-2025,74.7,74,B+,Pass,Average
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,S496,Asha_496,Female,25,Belagavi,Karnataka,BCom,1,2023,6,...,4,No,Yes,Placed,03-02-2025,63.4,63,B,Pass,Good
496,S497,Amit_497,Male,22,Dharwad,Karnataka,BSc,2,2024,4,...,4,Yes,Yes,Placed,22-09-2025,67.3,67,B,Pass,Excellent
497,S498,Nikhil_498,Female,20,Shivamogga,Karnataka,MBA,2,2025,3,...,5,Yes,Yes,Not Placed,02-05-2025,76.2,76,B+,Pass,Needs Improvement
498,S499,Manoj_499,Female,19,Dharwad,Karnataka,BCom,3,2025,2,...,5,Yes,Yes,Not Placed,27-03-2025,68.8,68,B,Pass,Excellent
499,S500,Amit_500,Male,19,Bengaluru,Karnataka,MCA,2,2023,5,...,5,Yes,Yes,Not Placed,11-02-2025,58.3,58,C,Pass,Needs Improvement

In [ ]:
clean_data.isnull().sum().sum()

np.int64(4)

In [ ]:
#data transformation
data.columns=data.columns.str.replace("_"," ")
data

,Student ID,Student Name,Gender,Age,City,State,Department,Semester,Admission Year,Study Hours,...,Projects Completed,Internship,Scholarship,Placement Status,Exam Date,Total Marks,Percentage,Grade,Pass Status,Remarks
0,S001,Anita_1,Male,19,Belagavi,Karnataka,MBA,1,2023,1,...,3,No,Yes,Placed,03-09-2025,70.7,70.7,B+,Pass,Needs Improvement
1,S002,Suresh_2,Male,24,Bengaluru,Karnataka,BCA,1,2023,5,...,1,Yes,No,Placed,04-10-2025,57.0,57.0,C,Pass,Good
2,S003,Suresh_3,Male,21,Hubballi,Karnataka,MBA,4,2024,8,...,3,No,No,Placed,26-03-2025,61.5,61.5,B,Pass,Good
3,S004,Asha_4,Female,25,Belagavi,Karnataka,MBA,1,2022,9,...,1,No,Yes,Not Placed,14-01-2025,77.3,77.3,B+,Pass,Excellent
4,S005,Deepa_5,Female,25,Bengaluru,Karnataka,MCA,3,2025,2,...,5,No,No,Not Placed,23-07-2025,74.7,74.7,B+,Pass,Average
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
500,S011,Rahul_11,Male,23,Mysuru,Karnataka,MBA,1,2024,2,...,2,No,Yes,Not Placed,25-04-2025,77.9,77.9,B+,Pass,Average
501,S087,Rohan_87,Female,18,Bengaluru,Karnataka,MCA,4,2025,6,...,2,Yes,Yes,Not Placed,24-07-2025,63.0,63.0,B,Pass,Good
502,S154,Vikram_154,Female,19,Mangaluru,Karnataka,BCom,4,2025,4,...,2,Yes,No,Placed,21-05-2025,60.0,60.0,B,Pass,Average
503,S259,Neha_259,Female,18,Hubballi,Karnataka,BCA,3,2025,1,...,2,Yes,Yes,Placed,05-10-2025,74.3,74.3,B+,Pass,Average
504,S332,Deepa_332,Male,19,Dharwad,Karnataka,MBA,4,2022,6,...,4,Yes,Yes,Not Placed,12-06-2025,84.0,84.0,A,Pass,Average

In [ ]:
data.columns =data.columns.str.replace(" ","_")
data

,Student_ID,Student_Name,Gender,Age,City,State,Department,Semester,Admission_Year,Study_Hours,...,Projects_Completed,Internship,Scholarship,Placement_Status,Exam_Date,Total_Marks,Percentage,Grade,Pass_Status,Remarks
0,S001,Anita_1,Male,19,Belagavi,Karnataka,MBA,1,2023,1,...,3,No,Yes,Placed,03-09-2025,70.7,70.7,B+,Pass,Needs Improvement
1,S002,Suresh_2,Male,24,Bengaluru,Karnataka,BCA,1,2023,5,...,1,Yes,No,Placed,04-10-2025,57.0,57.0,C,Pass,Good
2,S003,Suresh_3,Male,21,Hubballi,Karnataka,MBA,4,2024,8,...,3,No,No,Placed,26-03-2025,61.5,61.5,B,Pass,Good
3,S004,Asha_4,Female,25,Belagavi,Karnataka,MBA,1,2022,9,...,1,No,Yes,Not Placed,14-01-2025,77.3,77.3,B+,Pass,Excellent
4,S005,Deepa_5,Female,25,Bengaluru,Karnataka,MCA,3,2025,2,...,5,No,No,Not Placed,23-07-2025,74.7,74.7,B+,Pass,Average
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
500,S011,Rahul_11,Male,23,Mysuru,Karnataka,MBA,1,2024,2,...,2,No,Yes,Not Placed,25-04-2025,77.9,77.9,B+,Pass,Average
501,S087,Rohan_87,Female,18,Bengaluru,Karnataka,MCA,4,2025,6,...,2,Yes,Yes,Not Placed,24-07-2025,63.0,63.0,B,Pass,Good
502,S154,Vikram_154,Female,19,Mangaluru,Karnataka,BCom,4,2025,4,...,2,Yes,No,Placed,21-05-2025,60.0,60.0,B,Pass,Average
503,S259,Neha_259,Female,18,Hubballi,Karnataka,BCA,3,2025,1,...,2,Yes,Yes,Placed,05-10-2025,74.3,74.3,B+,Pass,Average
504,S332,Deepa_332,Male,19,Dharwad,Karnataka,MBA,4,2022,6,...,4,Yes,Yes,Not Placed,12-06-2025,84.0,84.0,A,Pass,Average

In [ ]:
data["Age"] = data["Age"].astype(int)
data

/tmp/ipykernel_526/3137543469.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data["Age"] = data["Age"].astype(int)

,Student_ID,Student_Name,Gender,Age,City,State,Department,Semester,Admission_Year,Study_Hours,...,Projects_Completed,Internship,Scholarship,Placement_Status,Exam_Date,Total_Marks,Percentage,Grade,Pass_Status,Remarks
0,S001,Anita_1,Male,19,Belagavi,Karnataka,MBA,1,2023,1,...,3,No,Yes,Placed,03-09-2025,70.7,70.7,B+,Pass,Needs Improvement
1,S002,Suresh_2,Male,24,Bengaluru,Karnataka,BCA,1,2023,5,...,1,Yes,No,Placed,04-10-2025,57.0,57.0,C,Pass,Good
2,S003,Suresh_3,Male,21,Hubballi,Karnataka,MBA,4,2024,8,...,3,No,No,Placed,26-03-2025,61.5,61.5,B,Pass,Good
3,S004,Asha_4,Female,25,Belagavi,Karnataka,MBA,1,2022,9,...,1,No,Yes,Not Placed,14-01-2025,77.3,77.3,B+,Pass,Excellent
4,S005,Deepa_5,Female,25,Bengaluru,Karnataka,MCA,3,2025,2,...,5,No,No,Not Placed,23-07-2025,74.7,74.7,B+,Pass,Average
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
500,S011,Rahul_11,Male,23,Mysuru,Karnataka,MBA,1,2024,2,...,2,No,Yes,Not Placed,25-04-2025,77.9,77.9,B+,Pass,Average
501,S087,Rohan_87,Female,18,Bengaluru,Karnataka,MCA,4,2025,6,...,2,Yes,Yes,Not Placed,24-07-2025,63.0,63.0,B,Pass,Good
502,S154,Vikram_154,Female,19,Mangaluru,Karnataka,BCom,4,2025,4,...,2,Yes,No,Placed,21-05-2025,60.0,60.0,B,Pass,Average
503,S259,Neha_259,Female,18,Hubballi,Karnataka,BCA,3,2025,1,...,2,Yes,Yes,Placed,05-10-2025,74.3,74.3,B+,Pass,Average
504,S332,Deepa_332,Male,19,Dharwad,Karnataka,MBA,4,2022,6,...,4,Yes,Yes,Not Placed,12-06-2025,84.0,84.0,A,Pass,Average

In [ ]:
data["Percentage"] = data["Percentage"].astype(float)
data

/tmp/ipykernel_526/1018609578.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data["Percentage"] = data["Percentage"].astype(float)

,Student_ID,Student_Name,Gender,Age,City,State,Department,Semester,Admission_Year,Study_Hours,...,Projects_Completed,Internship,Scholarship,Placement_Status,Exam_Date,Total_Marks,Percentage,Grade,Pass_Status,Remarks
0,S001,Anita_1,Male,19,Belagavi,Karnataka,MBA,1,2023,1,...,3,No,Yes,Placed,03-09-2025,70.7,70.0,B+,Pass,Needs Improvement
1,S002,Suresh_2,Male,24,Bengaluru,Karnataka,BCA,1,2023,5,...,1,Yes,No,Placed,04-10-2025,57.0,57.0,C,Pass,Good
2,S003,Suresh_3,Male,21,Hubballi,Karnataka,MBA,4,2024,8,...,3,No,No,Placed,26-03-2025,61.5,61.0,B,Pass,Good
3,S004,Asha_4,Female,25,Belagavi,Karnataka,MBA,1,2022,9,...,1,No,Yes,Not Placed,14-01-2025,77.3,77.0,B+,Pass,Excellent
4,S005,Deepa_5,Female,25,Bengaluru,Karnataka,MCA,3,2025,2,...,5,No,No,Not Placed,23-07-2025,74.7,74.0,B+,Pass,Average
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
500,S011,Rahul_11,Male,23,Mysuru,Karnataka,MBA,1,2024,2,...,2,No,Yes,Not Placed,25-04-2025,77.9,77.0,B+,Pass,Average
501,S087,Rohan_87,Female,18,Bengaluru,Karnataka,MCA,4,2025,6,...,2,Yes,Yes,Not Placed,24-07-2025,63.0,63.0,B,Pass,Good
502,S154,Vikram_154,Female,19,Mangaluru,Karnataka,BCom,4,2025,4,...,2,Yes,No,Placed,21-05-2025,60.0,60.0,B,Pass,Average
503,S259,Neha_259,Female,18,Hubballi,Karnataka,BCA,3,2025,1,...,2,Yes,Yes,Placed,05-10-2025,74.3,74.0,B+,Pass,Average
504,S332,Deepa_332,Male,19,Dharwad,Karnataka,MBA,4,2022,6,...,4,Yes,Yes,Not Placed,12-06-2025,84.0,84.0,A,Pass,Average

In [ ]:
data.duplicated()
data

,Student_ID,Student_Name,Gender,Age,City,State,Department,Semester,Admission_Year,Study_Hours,...,Projects_Completed,Internship,Scholarship,Placement_Status,Exam_Date,Total_Marks,Percentage,Grade,Pass_Status,Remarks
0,S001,Anita_1,Male,19,Belagavi,Karnataka,MBA,1,2023,1,...,3,No,Yes,Placed,03-09-2025,70.7,70.0,B+,Pass,Needs Improvement
1,S002,Suresh_2,Male,24,Bengaluru,Karnataka,BCA,1,2023,5,...,1,Yes,No,Placed,04-10-2025,57.0,57.0,C,Pass,Good
2,S003,Suresh_3,Male,21,Hubballi,Karnataka,MBA,4,2024,8,...,3,No,No,Placed,26-03-2025,61.5,61.0,B,Pass,Good
3,S004,Asha_4,Female,25,Belagavi,Karnataka,MBA,1,2022,9,...,1,No,Yes,Not Placed,14-01-2025,77.3,77.0,B+,Pass,Excellent
4,S005,Deepa_5,Female,25,Bengaluru,Karnataka,MCA,3,2025,2,...,5,No,No,Not Placed,23-07-2025,74.7,74.0,B+,Pass,Average
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
500,S011,Rahul_11,Male,23,Mysuru,Karnataka,MBA,1,2024,2,...,2,No,Yes,Not Placed,25-04-2025,77.9,77.0,B+,Pass,Average
501,S087,Rohan_87,Female,18,Bengaluru,Karnataka,MCA,4,2025,6,...,2,Yes,Yes,Not Placed,24-07-2025,63.0,63.0,B,Pass,Good
502,S154,Vikram_154,Female,19,Mangaluru,Karnataka,BCom,4,2025,4,...,2,Yes,No,Placed,21-05-2025,60.0,60.0,B,Pass,Average
503,S259,Neha_259,Female,18,Hubballi,Karnataka,BCA,3,2025,1,...,2,Yes,Yes,Placed,05-10-2025,74.3,74.0,B+,Pass,Average
504,S332,Deepa_332,Male,19,Dharwad,Karnataka,MBA,4,2022,6,...,4,Yes,Yes,Not Placed,12-06-2025,84.0,84.0,A,Pass,Average

In [ ]:
data.drop_duplicates()
data

,Student_ID,Student_Name,Gender,Age,City,State,Department,Semester,Admission_Year,Study_Hours,...,Projects_Completed,Internship,Scholarship,Placement_Status,Exam_Date,Total_Marks,Percentage,Grade,Pass_Status,Remarks
0,S001,Anita_1,Male,19,Belagavi,Karnataka,MBA,1,2023,1,...,3,No,Yes,Placed,03-09-2025,70.7,70.0,B+,Pass,Needs Improvement
1,S002,Suresh_2,Male,24,Bengaluru,Karnataka,BCA,1,2023,5,...,1,Yes,No,Placed,04-10-2025,57.0,57.0,C,Pass,Good
2,S003,Suresh_3,Male,21,Hubballi,Karnataka,MBA,4,2024,8,...,3,No,No,Placed,26-03-2025,61.5,61.0,B,Pass,Good
3,S004,Asha_4,Female,25,Belagavi,Karnataka,MBA,1,2022,9,...,1,No,Yes,Not Placed,14-01-2025,77.3,77.0,B+,Pass,Excellent
4,S005,Deepa_5,Female,25,Bengaluru,Karnataka,MCA,3,2025,2,...,5,No,No,Not Placed,23-07-2025,74.7,74.0,B+,Pass,Average
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
500,S011,Rahul_11,Male,23,Mysuru,Karnataka,MBA,1,2024,2,...,2,No,Yes,Not Placed,25-04-2025,77.9,77.0,B+,Pass,Average
501,S087,Rohan_87,Female,18,Bengaluru,Karnataka,MCA,4,2025,6,...,2,Yes,Yes,Not Placed,24-07-2025,63.0,63.0,B,Pass,Good
502,S154,Vikram_154,Female,19,Mangaluru,Karnataka,BCom,4,2025,4,...,2,Yes,No,Placed,21-05-2025,60.0,60.0,B,Pass,Average
503,S259,Neha_259,Female,18,Hubballi,Karnataka,BCA,3,2025,1,...,2,Yes,Yes,Placed,05-10-2025,74.3,74.0,B+,Pass,Average
504,S332,Deepa_332,Male,19,Dharwad,Karnataka,MBA,4,2022,6,...,4,Yes,Yes,Not Placed,12-06-2025,84.0,84.0,A,Pass,Average

In [ ]:
data["Total Marks"] = (data["Assignment_Score"] + data["Internal_Marks"] + data["Final_Exam_Marks"])
data

/tmp/ipykernel_526/718576915.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data["Total Marks"] = (data["Assignment_Score"] + data["Internal_Marks"] + data["Final_Exam_Marks"])

,Student_ID,Student_Name,Gender,Age,City,State,Department,Semester,Admission_Year,Study_Hours,...,Internship,Scholarship,Placement_Status,Exam_Date,Total_Marks,Percentage,Grade,Pass_Status,Remarks,Total Marks
0,S001,Anita_1,Male,19,Belagavi,Karnataka,MBA,1,2023,1,...,No,Yes,Placed,03-09-2025,70.7,70.0,B+,Pass,Needs Improvement,189.0
1,S002,Suresh_2,Male,24,Bengaluru,Karnataka,BCA,1,2023,5,...,Yes,No,Placed,04-10-2025,57.0,57.0,C,Pass,Good,146.0
2,S003,Suresh_3,Male,21,Hubballi,Karnataka,MBA,4,2024,8,...,No,No,Placed,26-03-2025,61.5,61.0,B,Pass,Good,201.0
3,S004,Asha_4,Female,25,Belagavi,Karnataka,MBA,1,2022,9,...,No,Yes,Not Placed,14-01-2025,77.3,77.0,B+,Pass,Excellent,210.0
4,S005,Deepa_5,Female,25,Bengaluru,Karnataka,MCA,3,2025,2,...,No,No,Not Placed,23-07-2025,74.7,74.0,B+,Pass,Average,231.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
500,S011,Rahul_11,Male,23,Mysuru,Karnataka,MBA,1,2024,2,...,No,Yes,Not Placed,25-04-2025,77.9,77.0,B+,Pass,Average,216.0
501,S087,Rohan_87,Female,18,Bengaluru,Karnataka,MCA,4,2025,6,...,Yes,Yes,Not Placed,24-07-2025,63.0,63.0,B,Pass,Good,207.0
502,S154,Vikram_154,Female,19,Mangaluru,Karnataka,BCom,4,2025,4,...,Yes,No,Placed,21-05-2025,60.0,60.0,B,Pass,Average,172.0
503,S259,Neha_259,Female,18,Hubballi,Karnataka,BCA,3,2025,1,...,Yes,Yes,Placed,05-10-2025,74.3,74.0,B+,Pass,Average,211.0
504,S332,Deepa_332,Male,19,Dharwad,Karnataka,MBA,4,2022,6,...,Yes,Yes,Not Placed,12-06-2025,84.0,84.0,A,Pass,Average,228.0

In [ ]:
data["External Marks"] = (data["Assignment_Score"] + data["Internal_Marks"]) - data["Final_Exam_Marks"]
data

/tmp/ipykernel_526/2388840991.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data["External Marks"] = (data["Assignment_Score"] + data["Internal_Marks"]) - data["Final_Exam_Marks"]

,Student_ID,Student_Name,Gender,Age,City,State,Department,Semester,Admission_Year,Study_Hours,...,Scholarship,Placement_Status,Exam_Date,Total_Marks,Percentage,Grade,Pass_Status,Remarks,Total Marks,External Marks
0,S001,Anita_1,Male,19,Belagavi,Karnataka,MBA,1,2023,1,...,Yes,Placed,03-09-2025,70.7,70.0,B+,Pass,Needs Improvement,189.0,29.0
1,S002,Suresh_2,Male,24,Bengaluru,Karnataka,BCA,1,2023,5,...,No,Placed,04-10-2025,57.0,57.0,C,Pass,Good,146.0,30.0
2,S003,Suresh_3,Male,21,Hubballi,Karnataka,MBA,4,2024,8,...,No,Placed,26-03-2025,61.5,61.0,B,Pass,Good,201.0,125.0
3,S004,Asha_4,Female,25,Belagavi,Karnataka,MBA,1,2022,9,...,Yes,Not Placed,14-01-2025,77.3,77.0,B+,Pass,Excellent,210.0,16.0
4,S005,Deepa_5,Female,25,Bengaluru,Karnataka,MCA,3,2025,2,...,No,Not Placed,23-07-2025,74.7,74.0,B+,Pass,Average,231.0,85.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
500,S011,Rahul_11,Male,23,Mysuru,Karnataka,MBA,1,2024,2,...,Yes,Not Placed,25-04-2025,77.9,77.0,B+,Pass,Average,216.0,24.0
501,S087,Rohan_87,Female,18,Bengaluru,Karnataka,MCA,4,2025,6,...,Yes,Not Placed,24-07-2025,63.0,63.0,B,Pass,Good,207.0,77.0
502,S154,Vikram_154,Female,19,Mangaluru,Karnataka,BCom,4,2025,4,...,No,Placed,21-05-2025,60.0,60.0,B,Pass,Average,172.0,92.0
503,S259,Neha_259,Female,18,Hubballi,Karnataka,BCA,3,2025,1,...,Yes,Placed,05-10-2025,74.3,74.0,B+,Pass,Average,211.0,83.0
504,S332,Deepa_332,Male,19,Dharwad,Karnataka,MBA,4,2022,6,...,Yes,Not Placed,12-06-2025,84.0,84.0,A,Pass,Average,228.0,36.0

In [ ]:
data["total_Percentage"] = (data["Total_Marks"]/ 100)*100
data

/tmp/ipykernel_526/726151781.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data["total_Percentage"] = (data["Total_Marks"]/ 100)*100

,Student_ID,Student_Name,Gender,Age,City,State,Department,Semester,Admission_Year,Study_Hours,...,Placement_Status,Exam_Date,Total_Marks,Percentage,Grade,Pass_Status,Remarks,Total Marks,External Marks,total_Percentage
0,S001,Anita_1,Male,19,Belagavi,Karnataka,MBA,1,2023,1,...,Placed,03-09-2025,70.7,70.0,B+,Pass,Needs Improvement,189.0,29.0,70.7
1,S002,Suresh_2,Male,24,Bengaluru,Karnataka,BCA,1,2023,5,...,Placed,04-10-2025,57.0,57.0,C,Pass,Good,146.0,30.0,57.0
2,S003,Suresh_3,Male,21,Hubballi,Karnataka,MBA,4,2024,8,...,Placed,26-03-2025,61.5,61.0,B,Pass,Good,201.0,125.0,61.5
3,S004,Asha_4,Female,25,Belagavi,Karnataka,MBA,1,2022,9,...,Not Placed,14-01-2025,77.3,77.0,B+,Pass,Excellent,210.0,16.0,77.3
4,S005,Deepa_5,Female,25,Bengaluru,Karnataka,MCA,3,2025,2,...,Not Placed,23-07-2025,74.7,74.0,B+,Pass,Average,231.0,85.0,74.7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
500,S011,Rahul_11,Male,23,Mysuru,Karnataka,MBA,1,2024,2,...,Not Placed,25-04-2025,77.9,77.0,B+,Pass,Average,216.0,24.0,77.9
501,S087,Rohan_87,Female,18,Bengaluru,Karnataka,MCA,4,2025,6,...,Not Placed,24-07-2025,63.0,63.0,B,Pass,Good,207.0,77.0,63.0
502,S154,Vikram_154,Female,19,Mangaluru,Karnataka,BCom,4,2025,4,...,Placed,21-05-2025,60.0,60.0,B,Pass,Average,172.0,92.0,60.0
503,S259,Neha_259,Female,18,Hubballi,Karnataka,BCA,3,2025,1,...,Placed,05-10-2025,74.3,74.0,B+,Pass,Average,211.0,83.0,74.3
504,S332,Deepa_332,Male,19,Dharwad,Karnataka,MBA,4,2022,6,...,Not Placed,12-06-2025,84.0,84.0,A,Pass,Average,228.0,36.0,84.0

In [ ]:
def grade(Total_Marks):
  if Total_Marks >= 90:
    return "A"
  elif Total_Marks >= 80:
    return "B"
  elif Total_Marks >= 70:
    return "C"
  elif Total_Marks >= 60:
    return "D"
  elif Total_Marks >= 50:
    return "E"
  else:
    return "F"
data["Grade"] = data["Percentage"].apply(grade)
data

/tmp/ipykernel_526/1402058951.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data["Grade"] = data["Percentage"].apply(grade)

,Student_ID,Student_Name,Gender,Age,City,State,Department,Semester,Admission_Year,Study_Hours,...,Placement_Status,Exam_Date,Total_Marks,Percentage,Grade,Pass_Status,Remarks,Total Marks,External Marks,total_Percentage
0,S001,Anita_1,Male,19,Belagavi,Karnataka,MBA,1,2023,1,...,Placed,03-09-2025,70.7,70.0,C,Pass,Needs Improvement,189.0,29.0,70.7
1,S002,Suresh_2,Male,24,Bengaluru,Karnataka,BCA,1,2023,5,...,Placed,04-10-2025,57.0,57.0,E,Pass,Good,146.0,30.0,57.0
2,S003,Suresh_3,Male,21,Hubballi,Karnataka,MBA,4,2024,8,...,Placed,26-03-2025,61.5,61.0,D,Pass,Good,201.0,125.0,61.5
3,S004,Asha_4,Female,25,Belagavi,Karnataka,MBA,1,2022,9,...,Not Placed,14-01-2025,77.3,77.0,C,Pass,Excellent,210.0,16.0,77.3
4,S005,Deepa_5,Female,25,Bengaluru,Karnataka,MCA,3,2025,2,...,Not Placed,23-07-2025,74.7,74.0,C,Pass,Average,231.0,85.0,74.7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
500,S011,Rahul_11,Male,23,Mysuru,Karnataka,MBA,1,2024,2,...,Not Placed,25-04-2025,77.9,77.0,C,Pass,Average,216.0,24.0,77.9
501,S087,Rohan_87,Female,18,Bengaluru,Karnataka,MCA,4,2025,6,...,Not Placed,24-07-2025,63.0,63.0,D,Pass,Good,207.0,77.0,63.0
502,S154,Vikram_154,Female,19,Mangaluru,Karnataka,BCom,4,2025,4,...,Placed,21-05-2025,60.0,60.0,D,Pass,Average,172.0,92.0,60.0
503,S259,Neha_259,Female,18,Hubballi,Karnataka,BCA,3,2025,1,...,Placed,05-10-2025,74.3,74.0,C,Pass,Average,211.0,83.0,74.3
504,S332,Deepa_332,Male,19,Dharwad,Karnataka,MBA,4,2022,6,...,Not Placed,12-06-2025,84.0,84.0,B,Pass,Average,228.0,36.0,84.0

In [ ]:
data.sort_values("Age")

,Student_ID,Student_Name,Gender,Age,City,State,Department,Semester,Admission_Year,Study_Hours,...,Placement_Status,Exam_Date,Total_Marks,Percentage,Grade,Pass_Status,Remarks,Total Marks,External Marks,total_Percentage
503,S259,Neha_259,Female,18,Hubballi,Karnataka,BCA,3,2025,1,...,Placed,05-10-2025,74.3,74.0,C,Pass,Average,211.0,83.0,74.3
29,S030,Asha_30,Female,18,Hubballi,Karnataka,MCA,1,2022,8,...,Placed,08-12-2025,72.0,72.0,C,Pass,Needs Improvement,239.0,117.0,72.0
30,S031,Asha_31,Female,18,Dharwad,Karnataka,BCA,1,2023,6,...,Placed,16-01-2025,63.8,63.0,D,Pass,Needs Improvement,188.0,110.0,63.8
33,S034,Rahul_34,Male,18,Hubballi,Karnataka,BCom,4,2024,3,...,Placed,27-06-2025,84.8,84.0,B,Pass,Excellent,243.0,83.0,84.8
478,S479,Suresh_479,Male,18,Belagavi,Karnataka,MBA,2,2023,6,...,Placed,28-06-2025,52.2,52.0,E,Pass,Excellent,157.0,49.0,52.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
93,S094,Sneha_94,Female,25,Shivamogga,Karnataka,BCA,1,2023,7,...,Not Placed,11-08-2025,57.3,57.0,E,Pass,Good,148.0,4.0,57.3
3,S004,Asha_4,Female,25,Belagavi,Karnataka,MBA,1,2022,9,...,Not Placed,14-01-2025,77.3,77.0,C,Pass,Excellent,210.0,16.0,77.3
4,S005,Deepa_5,Female,25,Bengaluru,Karnataka,MCA,3,2025,2,...,Not Placed,23-07-2025,74.7,74.0,C,Pass,Average,231.0,85.0,74.7
5,S006,Pooja_6,Male,25,Bengaluru,Karnataka,BCA,3,2023,4,...,Placed,15-07-2025,77.8,77.0,C,Pass,Average,205.0,55.0,77.8
495,S496,Asha_496,Female,25,Belagavi,Karnataka,BCom,1,2023,6,...,Placed,03-02-2025,63.4,63.0,D,Pass,Good,179.0,63.0,63.4

In [ ]:
data.sort_values("Study_Hours")

,Student_ID,Student_Name,Gender,Age,City,State,Department,Semester,Admission_Year,Study_Hours,...,Placement_Status,Exam_Date,Total_Marks,Percentage,Grade,Pass_Status,Remarks,Total Marks,External Marks,total_Percentage
0,S001,Anita_1,Male,19,Belagavi,Karnataka,MBA,1,2023,1,...,Placed,03-09-2025,70.7,70.0,C,Pass,Needs Improvement,189.0,29.0,70.7
475,S476,Deepa_476,Male,22,Hubballi,Karnataka,BCom,4,2022,1,...,Not Placed,22-05-2025,69.8,69.0,D,Pass,Good,215.0,61.0,69.8
461,S462,Ravi_462,Male,20,Bengaluru,Karnataka,MBA,2,2022,1,...,Placed,28-02-2025,65.5,65.0,D,Pass,Excellent,192.0,102.0,65.5
460,S461,Kiran_461,Female,19,Bengaluru,Karnataka,BCom,1,2024,1,...,Not Placed,04-11-2025,76.5,76.0,C,Pass,Needs Improvement,228.0,86.0,76.5
42,S043,Arjun_43,Female,21,Hubballi,Karnataka,MBA,2,2023,1,...,Placed,07-08-2025,72.7,72.0,C,Pass,Needs Improvement,196.0,20.0,72.7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
52,S053,Nikhil_53,Male,20,Mysuru,Karnataka,BCA,2,2024,10,...,Not Placed,08-09-2025,58.8,58.0,E,Pass,Good,181.0,71.0,58.8
483,S484,Kiran_484,Female,19,Hubballi,Karnataka,BCA,3,2023,10,...,Placed,26-04-2025,83.0,83.0,B,Pass,Good,252.0,86.0,83.0
456,S457,Priya_457,Male,22,Shivamogga,Karnataka,BCA,2,2023,10,...,Not Placed,01-03-2025,61.9,61.0,D,Pass,Good,181.0,95.0,61.9
468,S469,Neha_469,Male,19,Hubballi,Karnataka,MCA,3,2025,10,...,Not Placed,15-09-2025,79.0,79.0,C,Pass,Excellent,237.0,87.0,79.0
479,S480,Asha_480,Male,18,Bengaluru,Karnataka,BCom,3,2022,10,...,Placed,18-04-2025,62.8,62.0,D,Pass,Needs Improvement,182.0,48.0,62.8

In [ ]:
data.sort_values("Age",ascending= False)
data.sort_values("Percentage",ascending= False)
data.sort_values("Study_Hours",ascending= False)

,Student_ID,Student_Name,Gender,Age,City,State,Department,Semester,Admission_Year,Study_Hours,...,Exam_Date,Total_Marks,Percentage,Grade,Pass_Status,Remarks,Total Marks,External Marks,total_Percentage,rank
483,S484,Kiran_484,Female,19,Hubballi,Karnataka,BCA,3,2023,10,...,26-04-2025,83.0,83.0,B,Pass,Good,252.0,86.0,83.0,30.5
479,S480,Asha_480,Male,18,Bengaluru,Karnataka,BCom,3,2022,10,...,18-04-2025,62.8,62.0,D,Pass,Needs Improvement,182.0,48.0,62.8,327.0
456,S457,Priya_457,Male,22,Shivamogga,Karnataka,BCA,2,2023,10,...,01-03-2025,61.9,61.0,D,Pass,Good,181.0,95.0,61.9,346.5
468,S469,Neha_469,Male,19,Hubballi,Karnataka,MCA,3,2025,10,...,15-09-2025,79.0,79.0,C,Pass,Excellent,237.0,87.0,79.0,53.0
445,S446,Pooja_446,Male,24,Dharwad,Karnataka,MCA,1,2023,10,...,12-02-2025,55.3,55.0,E,Pass,Good,175.0,35.0,55.3,424.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
109,S110,Pooja_110,Female,20,Belagavi,Karnataka,BCA,2,2023,1,...,09-09-2025,79.1,79.0,C,Pass,Needs Improvement,255.0,95.0,79.1,53.0
106,S107,Suresh_107,Female,24,Shivamogga,Karnataka,MBA,2,2023,1,...,26-02-2025,76.8,76.0,C,Pass,Good,234.0,82.0,76.8,92.5
461,S462,Ravi_462,Male,20,Bengaluru,Karnataka,MBA,2,2022,1,...,28-02-2025,65.5,65.0,D,Pass,Excellent,192.0,102.0,65.5,274.5
503,S259,Neha_259,Female,18,Hubballi,Karnataka,BCA,3,2025,1,...,05-10-2025,74.3,74.0,C,Pass,Average,211.0,83.0,74.3,126.0
0,S001,Anita_1,Male,19,Belagavi,Karnataka,MBA,1,2023,1,...,03-09-2025,70.7,70.0,C,Pass,Needs Improvement,189.0,29.0,70.7,193.0

In [ ]:
data[data["Department"] == "BCA"]

,Student_ID,Student_Name,Gender,Age,City,State,Department,Semester,Admission_Year,Study_Hours,...,Placement_Status,Exam_Date,Total_Marks,Percentage,Grade,Pass_Status,Remarks,Total Marks,External Marks,total_Percentage
1,S002,Suresh_2,Male,24,Bengaluru,Karnataka,BCA,1,2023,5,...,Placed,04-10-2025,57.0,57.0,E,Pass,Good,146.0,30.0,57.0
5,S006,Pooja_6,Male,25,Bengaluru,Karnataka,BCA,3,2023,4,...,Placed,15-07-2025,77.8,77.0,C,Pass,Average,205.0,55.0,77.8
12,S013,Neha_13,Female,21,Belagavi,Karnataka,BCA,4,2022,8,...,Not Placed,26-12-2025,50.8,50.0,E,Pass,Good,164.0,78.0,50.8
20,S021,Manoj_21,Female,19,Bengaluru,Karnataka,BCA,1,2022,5,...,Placed,27-07-2025,71.4,71.0,C,Pass,Average,236.0,92.0,71.4
24,S025,Asha_25,Female,22,Mangaluru,Karnataka,BCA,2,2024,4,...,Not Placed,02-03-2025,71.9,71.0,C,Pass,Excellent,227.0,57.0,71.9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
486,S487,Kavya_487,Male,25,Belagavi,Karnataka,BCA,1,2024,7,...,Placed,27-02-2025,65.2,65.0,D,Pass,Good,211.0,117.0,65.2
489,S490,Divya_490,Male,18,Mysuru,Karnataka,BCA,1,2025,1,...,Placed,01-07-2025,66.0,66.0,D,Pass,Needs Improvement,203.0,131.0,66.0
492,S493,Divya_493,Male,18,Bengaluru,Karnataka,BCA,4,2022,9,...,Placed,05-06-2025,78.7,78.0,C,Pass,Needs Improvement,251.0,81.0,78.7
493,S494,Deepa_494,Male,24,Hubballi,Karnataka,BCA,4,2023,2,...,Not Placed,12-02-2025,75.1,75.0,C,Pass,Excellent,223.0,23.0,75.1
503,S259,Neha_259,Female,18,Hubballi,Karnataka,BCA,3,2025,1,...,Placed,05-10-2025,74.3,74.0,C,Pass,Average,211.0,83.0,74.3

In [ ]:
data[data["City"] == "Bengaluru"]

,Student_ID,Student_Name,Gender,Age,City,State,Department,Semester,Admission_Year,Study_Hours,...,Placement_Status,Exam_Date,Total_Marks,Percentage,Grade,Pass_Status,Remarks,Total Marks,External Marks,total_Percentage
1,S002,Suresh_2,Male,24,Bengaluru,Karnataka,BCA,1,2023,5,...,Placed,04-10-2025,57.0,57.0,E,Pass,Good,146.0,30.0,57.0
4,S005,Deepa_5,Female,25,Bengaluru,Karnataka,MCA,3,2025,2,...,Not Placed,23-07-2025,74.7,74.0,C,Pass,Average,231.0,85.0,74.7
5,S006,Pooja_6,Male,25,Bengaluru,Karnataka,BCA,3,2023,4,...,Placed,15-07-2025,77.8,77.0,C,Pass,Average,205.0,55.0,77.8
9,S010,Meena_10,Female,25,Bengaluru,Karnataka,MCA,4,2025,8,...,Placed,24-06-2025,67.6,67.0,D,Pass,Average,185.0,37.0,67.6
14,S015,Divya_15,Male,18,Bengaluru,Karnataka,MCA,2,2025,4,...,Not Placed,17-04-2025,68.9,68.0,D,Pass,Average,205.0,107.0,68.9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
485,S486,Rahul_486,Male,20,Bengaluru,Karnataka,MBA,2,2024,8,...,Placed,12-05-2025,71.6,71.0,C,Pass,Average,216.0,92.0,71.6
490,S491,Asha_491,Male,21,Bengaluru,Karnataka,BCom,1,2025,4,...,Not Placed,23-08-2025,61.7,61.0,D,Pass,Excellent,187.0,73.0,61.7
492,S493,Divya_493,Male,18,Bengaluru,Karnataka,BCA,4,2022,9,...,Placed,05-06-2025,78.7,78.0,C,Pass,Needs Improvement,251.0,81.0,78.7
499,S500,Amit_500,Male,19,Bengaluru,Karnataka,MCA,2,2023,5,...,Not Placed,11-02-2025,58.3,58.0,E,Pass,Needs Improvement,170.0,102.0,58.3
501,S087,Rohan_87,Female,18,Bengaluru,Karnataka,MCA,4,2025,6,...,Not Placed,24-07-2025,63.0,63.0,D,Pass,Good,207.0,77.0,63.0

In [ ]:
data[data["Percentage"] > 80]

,Student_ID,Student_Name,Gender,Age,City,State,Department,Semester,Admission_Year,Study_Hours,...,Placement_Status,Exam_Date,Total_Marks,Percentage,Grade,Pass_Status,Remarks,Total Marks,External Marks,total_Percentage
6,S007,Arjun_7,Female,23,Mangaluru,Karnataka,BCom,2,2023,2,...,Placed,16-10-2025,87.1,87.0,B,Pass,Good,281.0,81.0,87.1
21,S022,Suresh_22,Female,23,Bengaluru,Karnataka,BSc,1,2023,7,...,Not Placed,03-10-2025,84.5,84.0,B,Pass,Good,258.0,68.0,84.5
33,S034,Rahul_34,Male,18,Hubballi,Karnataka,BCom,4,2024,3,...,Placed,27-06-2025,84.8,84.0,B,Pass,Excellent,243.0,83.0,84.8
39,S040,Ravi_40,Male,22,Mysuru,Karnataka,BCom,4,2025,7,...,Not Placed,23-08-2025,86.7,86.0,B,Pass,Needs Improvement,239.0,45.0,86.7
54,S055,Pooja_55,Female,22,Shivamogga,Karnataka,MCA,1,2024,4,...,Placed,07-05-2025,82.5,82.0,B,Pass,Excellent,271.0,81.0,82.5
62,S063,Sneha_63,Male,20,Belagavi,Karnataka,BCom,3,2022,8,...,Placed,03-12-2025,81.0,81.0,B,Pass,Average,264.0,102.0,81.0
76,S077,Priya_77,Male,24,Bengaluru,Karnataka,BCom,1,2024,8,...,Not Placed,06-07-2025,87.9,87.0,B,Pass,Excellent,282.0,102.0,87.9
84,S085,Nikhil_85,Male,24,Dharwad,Karnataka,BCA,3,2022,7,...,Placed,06-12-2025,84.1,84.0,B,Pass,Good,231.0,49.0,84.1
88,S089,Neha_89,Female,24,Mangaluru,Karnataka,BSc,4,2023,8,...,Placed,21-05-2025,84.3,84.0,B,Pass,Average,254.0,104.0,84.3
96,S097,Meena_97,Male,19,Mysuru,Karnataka,MCA,4,2023,2,...,Placed,21-01-2025,85.2,85.0,B,Pass,Average,267.0,111.0,85.2
98,S099,Kiran_99,Male,24,Dharwad,Karnataka,MBA,2,2025,7,...,Placed,05-11-2025,83.1,83.0,B,Pass,Excellent,244.0,70.0,83.1
124,S125,Anita_125,Male,22,Bengaluru,Karnataka,MBA,1,2025,4,...,Not Placed,21-03-2025,85.9,85.0,B,Pass,Excellent,261.0,63.0,85.9
130,S131,Priya_131,Female,22,Belagavi,Karnataka,BCom,4,2024,1,...,Placed,18-05-2025,85.0,85.0,B,Pass,Good,239.0,63.0,85.0
132,S133,Meena_133,Female,24,Hubballi,Karnataka,BCom,3,2022,10,...,Placed,17-04-2025,85.7,85.0,B,Pass,Excellent,265.0,69.0,85.7
136,S137,Amit_137,Male,24,Dharwad,Karnataka,MCA,2,2023,9,...,Placed,06-09-2025,93.8,93.0,A,Pass,Needs Improvement,288.0,98.0,93.8
143,S144,Divya_144,Male,24,Dharwad,Karnataka,MBA,2,2023,2,...,Not Placed,01-11-2025,82.8,82.0,B,Pass,Good,241.0,87.0,82.8
159,S160,Rahul_160,Male,21,Mangaluru,Karnataka,BCom,1,2023,10,...,Placed,19-08-2025,83.8,83.0,B,Pass,Needs Improvement,229.0,35.0,83.8
195,S196,Anita_196,Female,23,Shivamogga,Karnataka,BCom,4,2022,2,...,Not Placed,03-04-2025,84.8,84.0,B,Pass,Needs Improvement,267.0,69.0,84.8
259,S260,Rohan_260,Male,22,Mysuru,Karnataka,MBA,1,2024,7,...,Placed,06-04-2025,89.0,89.0,B,Pass,Needs Improvement,268.0,68.0,89.0
295,S296,Kiran_296,Male,20,Belagavi,Karnataka,MCA,1,2022,3,...,Placed,04-08-2025,81.0,81.0,B,Pass,Good,250.0,82.0,81.0
322,S323,Neha_323,Female,22,Belagavi,Karnataka,BCom,1,2024,8,...,Not Placed,23-05-2025,87.6,87.0,B,Pass,Needs Improvement,275.0,95.0,87.6
331,S332,Deepa_332,Male,19,Dharwad,Karnataka,MBA,4,2022,6,...,Not Placed,12-06-2025,84.0,84.0,B,Pass,Average,228.0,36.0,84.0
338,S339,Rahul_339,Male,22,Mysuru,Karnataka,BSc,1,2025,10,...,Not Placed,26-08-2025,81.4,81.0,B,Pass,Good,233.0,33.0,81.4
347,S348,Arjun_348,Male,24,Shivamogga,Karnataka,BCom,2,2022,9,...,Placed,22-06-2025,87.6,87.0,B,Pass,Needs Improvement,270.0,90.0,87.6
356,S357,Meena_357,Male,24,Hubballi,Karnataka,BSc,2,2023,9,...,Not Placed,28-12-2025,83.8,83.0,B,Pass,Good,258.0,128.0,83.8
367,S368,Asha_368,Female,19,Dharwad,Karnataka,BCom,3,2022,7,...,Not Placed,18-09-2025,82.4,82.0,B,Pass,Needs Improvement,269.0,85.0,82.4
371,S372,Meena_372,Male,19,Mysuru,Karnataka,BCom,4,2024,3,...,Placed,17-05-2025,83.3,83.0,B,Pass,Needs Improvement,255.0,113.0,83.3
375,S376,Pooja_376,Female,19,Bengaluru,Karnataka,BSc,4,2023,3,...,Not Placed,03-03-2025,88.1,88.0,B,Pass,Good,275.0,77.0,88.1
387,S388,Rohan_388,Male,18,Dharwad,Karnataka,MCA,4,2024,8,...,Placed,16-04-2025,81.8,81.0,B,Pass,Average,241.0,91.0,81.8
393,S394,Anita_394,Male,21,Hubballi,Karnataka,MBA,4,2023,1,...,Not Placed,12-02-2025,82.2,82.0,B,Pass,Needs Improvement,232.0,78.0,82.2
396,S397,Asha_397,Female,23,Belagavi,Karnataka,MBA,1,2023,8,...,Not Placed,07-12-2025,83.0,83.0,B,Pass,Excellent,227.0,49.0,83.0
400,S401,Manoj_401,Male,21,Mysuru,Karnataka,MCA,1,2024,4,...,Not Placed,06-01-2025,86.0,86.0,B,Pass,Excellent,269.0,73.0,86.0
410,S411,Manoj_411,Male,20,Mysuru,Karnataka,BSc,3,2022,7,...,Placed,04-05-2025,87.1,87.0,B,Pass,Needs Improvement,260.0,84.0,87.1
412,S413,Anita_413,Female,22,Shivamogga,Karnataka,MCA,4,2024,9,...,Not Placed,10-05-2025,81.4,81.0,B,Pass,Average,235.0,59.0,81.4
418,S419,Anita_419,Female,22,Belagavi,Karnataka,MBA,1,2024,1,...,Not Placed,15-05-2025,90.4,90.0,A,Pass,Good,275.0,99.0,90.4
423,S424,Suresh_424,Female,23,Hubballi,Karnataka,BCA,4,2022,7,...,Not Placed,22-04-2025,88.7,88.0,B,Pass,Good,252.0,80.0,88.7
427,S428,Arjun_428,Female,22,Dharwad,Karnataka,MCA,1,2024,9,...,Not Placed,27-01-2025,81.2,81.0,B,Pass,Average,243.0,47.0,81.2
429,S430,Neha_430,Male,22,Dharwad,Karnataka,BSc,4,2024,7,...,Placed,18-09-2025,87.8,87.0,B,Pass,Excellent,262.0,88.0,87.8
435,S436,Rahul_436,Female,19,Dharwad,Karnataka,MCA,4,2023,1,...,Not Placed,14-06-2025,83.0,83.0,B,Pass,Good,229.0,51.0,83.0
457,S458,Priya_458,Female,18,Belagavi,Karnataka,BCom,1,2023,7,...,Placed,05-04-2025,85.2,85.0,B,Pass,Good,257.0,109.0,85.2
467,S468,Asha_468,Male,23,Belagavi,Karnataka,MCA,4,2022,8,...,Placed,03-10-2025,88.7,88.0,B,Pass,Excellent,282.0,116.0,88.7
481,S482,Sneha_482,Female,24,Mangaluru,Karnataka,BCom,3,2025,9,...,Not Placed,07-12-2025,83.9,83.0,B,Pass,Average,271.0,105.0,83.9
483,S484,Kiran_484,Female,19,Hubballi,Karnataka,BCA,3,2023,10,...,Placed,26-04-2025,83.0,83.0,B,Pass,Good,252.0,86.0,83.0
504,S332,Deepa_332,Male,19,Dharwad,Karnataka,MBA,4,2022,6,...,Not Placed,12-06-2025,84.0,84.0,B,Pass,Average,228.0,36.0,84.0

In [ ]:
data.groupby("Department")["Percentage"].sum()

Department
BCA     6214.0
BCom    7508.0
BSc     6420.0
MBA     6783.0
MCA     6240.0
Name: Percentage, dtype: float64

In [ ]:
data.groupby("Gender")["Attendance"].mean()

Gender
Female    76.251029
Male      76.902724
Name: Attendance, dtype: float64

In [ ]:
data.groupby("Department").agg({"Percentage" :["mean","count","max","min"],"Attendance":"mean"})

           Percentage                   Attendance
                 mean count   max   min       mean
Department
BCA         66.106383    94  88.0  40.0  78.063830
BCom        66.442478   113  87.0  42.0  74.451327
BSc         65.510204    98  88.0  41.0  77.295918
MBA         66.500000   102  90.0  40.0  76.049020
MCA         67.096774    93  93.0  39.0  77.526882

In [ ]:
data["rank"] = data["Percentage"].rank(ascending = False)
data

/tmp/ipykernel_526/89231429.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data["rank"] = data["Percentage"].rank(ascending = False)

,Student_ID,Student_Name,Gender,Age,City,State,Department,Semester,Admission_Year,Study_Hours,...,Exam_Date,Total_Marks,Percentage,Grade,Pass_Status,Remarks,Total Marks,External Marks,total_Percentage,rank
0,S001,Anita_1,Male,19,Belagavi,Karnataka,MBA,1,2023,1,...,03-09-2025,70.7,70.0,C,Pass,Needs Improvement,189.0,29.0,70.7,193.0
1,S002,Suresh_2,Male,24,Bengaluru,Karnataka,BCA,1,2023,5,...,04-10-2025,57.0,57.0,E,Pass,Good,146.0,30.0,57.0,405.5
2,S003,Suresh_3,Male,21,Hubballi,Karnataka,MBA,4,2024,8,...,26-03-2025,61.5,61.0,D,Pass,Good,201.0,125.0,61.5,346.5
3,S004,Asha_4,Female,25,Belagavi,Karnataka,MBA,1,2022,9,...,14-01-2025,77.3,77.0,C,Pass,Excellent,210.0,16.0,77.3,77.5
4,S005,Deepa_5,Female,25,Bengaluru,Karnataka,MCA,3,2025,2,...,23-07-2025,74.7,74.0,C,Pass,Average,231.0,85.0,74.7,126.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
500,S011,Rahul_11,Male,23,Mysuru,Karnataka,MBA,1,2024,2,...,25-04-2025,77.9,77.0,C,Pass,Average,216.0,24.0,77.9,77.5
501,S087,Rohan_87,Female,18,Bengaluru,Karnataka,MCA,4,2025,6,...,24-07-2025,63.0,63.0,D,Pass,Good,207.0,77.0,63.0,309.0
502,S154,Vikram_154,Female,19,Mangaluru,Karnataka,BCom,4,2025,4,...,21-05-2025,60.0,60.0,D,Pass,Average,172.0,92.0,60.0,363.5
503,S259,Neha_259,Female,18,Hubballi,Karnataka,BCA,3,2025,1,...,05-10-2025,74.3,74.0,C,Pass,Average,211.0,83.0,74.3,126.0
504,S332,Deepa_332,Male,19,Dharwad,Karnataka,MBA,4,2022,6,...,12-06-2025,84.0,84.0,B,Pass,Average,228.0,36.0,84.0,23.0

In [ ]:
data.groupby("Department")["Percentage"].sum()

Department
BCA     6214.0
BCom    7508.0
BSc     6420.0
MBA     6783.0
MCA     6240.0
Name: Percentage, dtype: float64

In [ ]:
data.head()

,Student_ID,Student_Name,Gender,Age,City,State,Department,Semester,Admission_Year,Study_Hours,...,Exam_Date,Total_Marks,Percentage,Grade,Pass_Status,Remarks,Total Marks,External Marks,total_Percentage,rank
0,S001,Anita_1,Male,19,Belagavi,Karnataka,MBA,1,2023,1,...,03-09-2025,70.7,70.0,C,Pass,Needs Improvement,189.0,29.0,70.7,193.0
1,S002,Suresh_2,Male,24,Bengaluru,Karnataka,BCA,1,2023,5,...,04-10-2025,57.0,57.0,E,Pass,Good,146.0,30.0,57.0,405.5
2,S003,Suresh_3,Male,21,Hubballi,Karnataka,MBA,4,2024,8,...,26-03-2025,61.5,61.0,D,Pass,Good,201.0,125.0,61.5,346.5
3,S004,Asha_4,Female,25,Belagavi,Karnataka,MBA,1,2022,9,...,14-01-2025,77.3,77.0,C,Pass,Excellent,210.0,16.0,77.3,77.5
4,S005,Deepa_5,Female,25,Bengaluru,Karnataka,MCA,3,2025,2,...,23-07-2025,74.7,74.0,C,Pass,Average,231.0,85.0,74.7,126.0

In [ ]:
data.groupby("Department")["Student_Name"].count()

Department
BCA      94
BCom    113
BSc      98
MBA     102
MCA      93
Name: Student_Name, dtype: int64

In [ ]:
data[data["Exam_Date"] > "05-07-2025"]

,Student_ID,Student_Name,Gender,Age,City,State,Department,Semester,Admission_Year,Study_Hours,...,Exam_Date,Total_Marks,Percentage,Grade,Pass_Status,Remarks,Total Marks,External Marks,total_Percentage,rank
2,S003,Suresh_3,Male,21,Hubballi,Karnataka,MBA,4,2024,8,...,26-03-2025,61.5,61.0,D,Pass,Good,201.0,125.0,61.5,346.5
3,S004,Asha_4,Female,25,Belagavi,Karnataka,MBA,1,2022,9,...,14-01-2025,77.3,77.0,C,Pass,Excellent,210.0,16.0,77.3,77.5
4,S005,Deepa_5,Female,25,Bengaluru,Karnataka,MCA,3,2025,2,...,23-07-2025,74.7,74.0,C,Pass,Average,231.0,85.0,74.7,126.0
5,S006,Pooja_6,Male,25,Bengaluru,Karnataka,BCA,3,2023,4,...,15-07-2025,77.8,77.0,C,Pass,Average,205.0,55.0,77.8,77.5
6,S007,Arjun_7,Female,23,Mangaluru,Karnataka,BCom,2,2023,2,...,16-10-2025,87.1,87.0,B,Pass,Good,281.0,81.0,87.1,9.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
500,S011,Rahul_11,Male,23,Mysuru,Karnataka,MBA,1,2024,2,...,25-04-2025,77.9,77.0,C,Pass,Average,216.0,24.0,77.9,77.5
501,S087,Rohan_87,Female,18,Bengaluru,Karnataka,MCA,4,2025,6,...,24-07-2025,63.0,63.0,D,Pass,Good,207.0,77.0,63.0,309.0
502,S154,Vikram_154,Female,19,Mangaluru,Karnataka,BCom,4,2025,4,...,21-05-2025,60.0,60.0,D,Pass,Average,172.0,92.0,60.0,363.5
503,S259,Neha_259,Female,18,Hubballi,Karnataka,BCA,3,2025,1,...,05-10-2025,74.3,74.0,C,Pass,Average,211.0,83.0,74.3,126.0
504,S332,Deepa_332,Male,19,Dharwad,Karnataka,MBA,4,2022,6,...,12-06-2025,84.0,84.0,B,Pass,Average,228.0,36.0,84.0,23.0

In [ ]:
data.shape

(500, 29)

In [ ]:
data["Percentage"].mean()

np.float64(66.33)

In [ ]:
data["Percentage"].max()

93.0

In [ ]:
data["Percentage"].min()

39.0

In [ ]:
data["Percentage"].sum()

np.float64(33165.0)

In [ ]:
data["Grade"].mode()

0    D
Name: Grade, dtype: object

In [ ]:
#find top 10 students
data.sort_values("Percentage",ascending=False).head(10)

,Student_ID,Student_Name,Gender,Age,City,State,Department,Semester,Admission_Year,Study_Hours,...,Exam_Date,Total_Marks,Percentage,Grade,Pass_Status,Remarks,Total Marks,External Marks,total_Percentage,rank
136,S137,Amit_137,Male,24,Dharwad,Karnataka,MCA,2,2023,9,...,06-09-2025,93.8,93.0,A,Pass,Needs Improvement,288.0,98.0,93.8,1.0
418,S419,Anita_419,Female,22,Belagavi,Karnataka,MBA,1,2024,1,...,15-05-2025,90.4,90.0,A,Pass,Good,275.0,99.0,90.4,2.0
259,S260,Rohan_260,Male,22,Mysuru,Karnataka,MBA,1,2024,7,...,06-04-2025,89.0,89.0,B,Pass,Needs Improvement,268.0,68.0,89.0,3.0
375,S376,Pooja_376,Female,19,Bengaluru,Karnataka,BSc,4,2023,3,...,03-03-2025,88.1,88.0,B,Pass,Good,275.0,77.0,88.1,5.0
423,S424,Suresh_424,Female,23,Hubballi,Karnataka,BCA,4,2022,7,...,22-04-2025,88.7,88.0,B,Pass,Good,252.0,80.0,88.7,5.0
467,S468,Asha_468,Male,23,Belagavi,Karnataka,MCA,4,2022,8,...,03-10-2025,88.7,88.0,B,Pass,Excellent,282.0,116.0,88.7,5.0
410,S411,Manoj_411,Male,20,Mysuru,Karnataka,BSc,3,2022,7,...,04-05-2025,87.1,87.0,B,Pass,Needs Improvement,260.0,84.0,87.1,9.5
6,S007,Arjun_7,Female,23,Mangaluru,Karnataka,BCom,2,2023,2,...,16-10-2025,87.1,87.0,B,Pass,Good,281.0,81.0,87.1,9.5
76,S077,Priya_77,Male,24,Bengaluru,Karnataka,BCom,1,2024,8,...,06-07-2025,87.9,87.0,B,Pass,Excellent,282.0,102.0,87.9,9.5
322,S323,Neha_323,Female,22,Belagavi,Karnataka,BCom,1,2024,8,...,23-05-2025,87.6,87.0,B,Pass,Needs Improvement,275.0,95.0,87.6,9.5

In [ ]:
data.sort_values("Percentage",ascending= False).tail(10)

,Student_ID,Student_Name,Gender,Age,City,State,Department,Semester,Admission_Year,Study_Hours,...,Exam_Date,Total_Marks,Percentage,Grade,Pass_Status,Remarks,Total Marks,External Marks,total_Percentage,rank
198,S199,Ravi_199,Female,25,Mangaluru,Karnataka,BCom,2,2024,6,...,18-02-2025,44.8,44.0,F,Fail,Needs Improvement,141.0,69.0,44.8,491.0
268,S269,Meena_269,Male,22,Mysuru,Karnataka,BSc,3,2025,3,...,13-05-2025,43.4,43.0,F,Fail,Excellent,129.0,53.0,43.4,493.5
99,S100,Kiran_100,Male,19,Mysuru,Karnataka,BCom,1,2024,10,...,25-12-2025,43.3,43.0,F,Fail,Good,143.0,53.0,43.3,493.5
441,S442,Priya_442,Male,25,Bengaluru,Karnataka,MCA,1,2023,1,...,08-05-2025,43.1,43.0,F,Fail,Average,129.0,43.0,43.1,493.5
45,S046,Kavya_46,Male,18,Mysuru,Karnataka,BCom,4,2024,2,...,21-09-2025,43.5,43.0,F,Fail,Needs Improvement,124.0,28.0,43.5,493.5
157,S158,Manoj_158,Female,23,Bengaluru,Karnataka,BCom,1,2023,3,...,19-04-2025,42.5,42.0,F,Fail,Needs Improvement,125.0,51.0,42.5,496.0
267,S268,Kiran_268,Male,20,Hubballi,Karnataka,BSc,1,2024,6,...,02-02-2025,41.5,41.0,F,Fail,Average,125.0,45.0,41.5,497.0
206,S207,Manoj_207,Male,24,Mangaluru,Karnataka,BCA,4,2024,2,...,22-02-2025,40.8,40.0,F,Fail,Average,138.0,68.0,40.8,498.5
74,S075,Kiran_75,Male,19,Shivamogga,Karnataka,MBA,3,2023,9,...,07-04-2025,40.5,40.0,F,Fail,Excellent,123.0,53.0,40.5,498.5
281,S282,Neha_282,Female,19,Dharwad,Karnataka,MCA,4,2022,4,...,13-05-2025,39.2,39.0,F,Fail,Needs Improvement,113.0,47.0,39.2,500.0

In [ ]:
data.groupby("Department")["Percentage"].mean()

Department
BCA     66.106383
BCom    66.442478
BSc     65.510204
MBA     66.500000
MCA     67.096774
Name: Percentage, dtype: float64

In [ ]:
data["City"].value_counts()

City
Bengaluru     79
Shivamogga    74
Mangaluru     73
Mysuru        73
Dharwad       70
Belagavi      67
Hubballi      64
Name: count, dtype: int64

In [ ]:
data["Grade"].value_counts()

Grade
D    172
C    151
E    104
B     45
F     26
A      2
Name: count, dtype: int64